import Mathlib.Algebra.FreeMonoid.Basic

namespace TraceTheory

variable {α : Type*}

/-- An independence is a finite, irreflexive, and symmetric relation. -/
structure Independence (α : Type*) where
  /-- The independence relation. -/
  rel : α → α → Prop
  irrefl : ∀ a, ¬ rel a a
  symm : ∀ a b, rel a b → rel b a

/-- A dependence is a finite, reflexive, and symmetric relation. -/
structure Dependence (α : Type*) where
  /-- The dependence relation. -/
  rel : α → α → Prop
  refl : ∀ a, rel a a
  symm: ∀ a b, rel a b → rel b a

namespace Independence

/-- The Dependence relation induced by an Independence `I`. -/
def inducedDependence {α : Type*} (I : Independence α) : Dependence α where
  rel := fun a b => ¬ I.rel a b
  refl := by
    intro a
    exact I.irrefl a
  symm := by
    intro a b hab hba
    exact hab (I.symm b a hba)

/-- Strings `x` and `y` are independent if every symbol in `x` is independent of
  every symbol in `y`. -/
@[simp]
def Independent (I : Independence α) (x y : List α) := ∀ a ∈ x, ∀ b ∈ y, I.rel a b

/-- The binary relation such that for strings `x, y` and independent symbols `a, b`,
  `x ++ [a, b] ++ y` is related to `x ++ [b, a] ++ y`. -/
inductive SwapOnce (I : Independence α) : List α → List α → Prop
  | swap (x y : List α) (a b : α) : I.rel a b → SwapOnce I (x ++ [a, b] ++ y) (x ++ [b, a] ++ y)

end Independence

namespace Dependence

/-- The Independence relation induced by a Dependence `D`. -/
def inducedIndependence {α : Type*} (D : Dependence α) : Independence α where
  rel := fun a b => ¬D.rel a b
  irrefl := by
    intro a h
    exact h (D.refl a)
  symm := by
    intro a b hab hba
    exact hab (D.symm b a hba)

end Dependence

/-- The trace equivalence relation is the least congruence such that for all independent symbols
  `a` and `b`, `[a, b]` is equivalent to `[b, a]`.

  The relation is inductively generated by:
  - `swap`: If `I.rel a b`, then `[a, b]` is equivalent to `[b, a]` (the underlying relation).
  - `refl`: Every word `x` is equivalent to itself.
  - `symm`: If `x` is equivalent to `y`, then `y` is equivalent to `x`.
  - `trans`: If `x` is equivalent to `y` and `y` is equivalent to `z`, then `x` is
  equivalent to `z`.
  - `compat`: If `x` is equivalent to `y` and `z` is equivalent to `w`, then `x ++ z`
  is equivalent to `y ++ w` (compatibility with composition).

  This serves as the basis for the `TraceSetoid` structure. -/
inductive TraceEqv (I : Independence α) : List α → List α → Prop
  | swap : ∀ a b, I.rel a b → TraceEqv I [a, b] [b, a]
  | refl : ∀ x, TraceEqv I x x
  | symm : ∀ {x y}, TraceEqv I x y → TraceEqv I y x
  | trans : ∀ {x y z},
      TraceEqv I x y →
      TraceEqv I y z →
      TraceEqv I x z
  | compat : ∀ {x y z w},
      TraceEqv I x y →
      TraceEqv I z w →
      TraceEqv I (x ++ z) (y ++ w)

instance : CancelMonoid (List α) where
  one := List.nil
  mul := List.append
  mul_assoc := List.append_assoc
  mul_one := List.append_nil
  one_mul := List.nil_append
  mul_left_cancel := by
    intro a b c heq
    exact List.append_cancel_left heq
  mul_right_cancel := by
    intro a b c heq
    exact List.append_cancel_right heq

/-- The setoid structure on strings defined by the trace equivalence relation `TraceEqv`.
  This serves as the basis for constructing the quotient type `Trace`. -/
def TraceSetoid (I : Independence α) : Setoid (List α) where
  r := TraceEqv I
  iseqv := ⟨TraceEqv.refl, TraceEqv.symm, TraceEqv.trans⟩

/-- The type of Mazurkiewicz traces, defined as the quotient of the free monoid
  by the trace equivalence relation induced by `I`. -/
def Trace (I : Independence α) := Quotient (TraceSetoid I)

namespace Trace

variable {I : Independence α} [DecidableEq α]

/-- Composition (concatenation) of traces. This is induced by the concatenation
  operation on the underlying strings. -/
@[simp]
def mul : Trace I -> Trace I -> Trace I :=
  Quotient.lift₂
    (fun x y => ⟦x ++ y⟧)
    (by
      intro a₁ b₁ a₂ b₂ ha hb
      apply Quotient.sound
      exact ha.compat hb
    )

/-- The empty trace, represented by the equivalence class of the empty list. -/
def one := Quotient.mk (TraceSetoid I) []

instance : Monoid (Trace I) where
  mul := mul
  one := one
  mul_assoc := by
    intro t₁ t₂ t₃
    refine Quotient.inductionOn₃ t₁ t₂ t₃ (fun x₁ x₂ x₃ => ?_)
    apply Quotient.sound
    rw [List.append_assoc]
    exact TraceEqv.refl _
  one_mul := by
    intro t
    refine Quotient.inductionOn t (fun x => ?_)
    apply Quotient.sound
    rw [List.nil_append]
    exact TraceEqv.refl _
  mul_one := by
    intro t
    refine Quotient.inductionOn t (fun x => ?_)
    apply Quotient.sound
    rw [List.append_nil]
    exact TraceEqv.refl _

/-- The natural homomorphism from the free monoid `List α` to the trace monoid `Trace I`. -/
def mk' (I : Independence α) : List α →* Trace I where
  toFun := Quotient.mk (TraceSetoid I)
  map_one' := rfl
  map_mul' := fun _ _ => rfl

omit [DecidableEq α] in
@[simp]
theorem mk'_nil : mk' I [] = 1 := map_one _

/-- The prefix relation on traces. A trace `u` is a prefix of `w` if there exists
  a trace `v` such that `u` concatenated with `v` equals `w`. -/
def IsPrefix (I : Independence α) (u w : Trace I) := ∃ v, u * v = w

end Trace

end TraceTheory
