import TraceTheory.Zielonka.Merge

namespace TraceTheory.Zielonka

open Classical
noncomputable section

set_option backward.isDefEq.respectTransparency false

variable {α M : Type} {n : ℕ} {I : Independence α} {w : List α}
variable (d : Distribution α n)

/-- The primary events selected by a finite set of process indices. -/
def primaryCut (I : Independence α) (w : List α) (p : Fin n)
    (R : Finset (Fin n)) : Finset (Event w) :=
  R.biUnion (fun r => (primary d I w p r).toFinset)

@[simp]
theorem mem_primaryCut (p : Fin n) (R : Finset (Fin n)) (e : Event w) :
    e ∈ primaryCut d I w p R ↔ ∃ r ∈ R, primary d I w p r = some e := by
  simp [primaryCut, Option.mem_toFinset, eq_comm]

theorem primaryCut_subset (p : Fin n) (R : Finset (Fin n)) :
    primaryCut d I w p R ⊆ primaryEvents d I w p := by
  intro e he
  obtain ⟨r, _, hr⟩ := (mem_primaryCut d p R e).mp he
  exact (mem_primaryEvents d p e).mpr ⟨r, hr⟩

/-- Every subset of primary events has a finite index representation, even with aliases. -/
theorem exists_primaryCut (p : Fin n) (s : Finset (Event w))
    (hs : s ⊆ primaryEvents d I w p) : ∃ R, primaryCut d I w p R = s := by
  refine ⟨Finset.univ.filter (fun r => ∃ e ∈ s, primary d I w p r = some e), ?_⟩
  ext e
  simp only [mem_primaryCut, Finset.mem_filter, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨r, ⟨f, hf, hr⟩, he⟩
    have hfe := Option.some.inj (hr.symm.trans he)
    simpa [hfe] using hf
  · intro he
    obtain ⟨r, hr⟩ := (mem_primaryEvents d p e).mp (hs he)
    exact ⟨r, ⟨e, he, hr⟩, hr⟩

theorem primaryCut_union (p : Fin n) (R S : Finset (Fin n)) :
    primaryCut d I w p (R ∪ S) = primaryCut d I w p R ∪ primaryCut d I w p S := by
  ext e
  simp only [mem_primaryCut, Finset.mem_union]
  constructor
  · rintro ⟨r, hr | hr, he⟩
    · exact .inl ⟨r, hr, he⟩
    · exact .inr ⟨r, hr, he⟩
  · rintro (⟨r, hr, he⟩ | ⟨r, hr, he⟩)
    · exact ⟨r, .inl hr, he⟩
    · exact ⟨r, .inr hr, he⟩

/-- Common primary indices describe intersections with joint process views. -/
def commonIndices (I : Independence α) (w : List α) (p : Fin n)
    (P : Finset (Fin n)) : Finset (Fin n) :=
  Finset.univ.filter (fun r => ∃ q ∈ P, ∃ e,
    primary d I w p r = some e ∧ e ∈ primaryEvents d I w q)

theorem commonIndices_cut (p : Fin n) (P : Finset (Fin n)) :
    primaryCut d I w p (commonIndices d I w p P) =
      P.biUnion (fun q => primaryEvents d I w p ∩ primaryEvents d I w q) := by
  ext e
  simp only [mem_primaryCut, commonIndices, Finset.mem_filter, Finset.mem_univ,
    true_and, Finset.mem_biUnion, Finset.mem_inter]
  constructor
  · rintro ⟨r, ⟨q, hq, f, hf, hfq⟩, he⟩
    have hfe := Option.some.inj (hf.symm.trans he)
    subst f
    exact ⟨q, hq, (mem_primaryEvents d p e).mpr ⟨r, he⟩, hfq⟩
  · rintro ⟨q, hq, hep, heq⟩
    obtain ⟨r, hr⟩ := (mem_primaryEvents d p e).mp hep
    exact ⟨r, ⟨q, hq, e, hr, heq⟩, hr⟩

theorem down_biUnion {β : Type} [DecidableEq β] (P : Finset β)
    (s : β → Finset (Event w)) : down I (P.biUnion s) = P.biUnion (fun p => down I (s p)) := by
  ext e
  simp only [mem_down, Finset.mem_biUnion]
  constructor
  · rintro ⟨f, ⟨p, hp, hf⟩, hef⟩
    exact ⟨p, hp, f, hf, hef⟩
  · rintro ⟨p, hp, f, hf, hef⟩
    exact ⟨f, ⟨p, hp, hf⟩, hef⟩

/-- Corollary 1.33(ii): intersections with a joint view are generated by primary events. -/
theorem view_inter_jointView (hcompat : d.Compatible I) (p : Fin n) (P : Finset (Fin n)) :
    view d I w p ∩ jointView d I w P =
      down I (primaryCut d I w p (commonIndices d I w p P)) := by
  rw [commonIndices_cut, down_biUnion]
  ext e
  simp only [Finset.mem_inter, mem_jointView, Finset.mem_biUnion]
  constructor
  · rintro ⟨hep, q, hq, heq⟩
    refine ⟨q, hq, ?_⟩
    rw [← view_inter_eq_down_primary d hcompat p q]
    exact Finset.mem_inter.mpr ⟨hep, heq⟩
  · rintro ⟨q, hq, he⟩
    rw [← view_inter_eq_down_primary d hcompat p q] at he
    exact ⟨(Finset.mem_inter.mp he).1, q, hq, (Finset.mem_inter.mp he).2⟩

variable [Monoid M] [DecidableEq α] (φ : Trace I →* M)

/-- The finite-monoid effect of a residue, replacing the PDF's state transformer. -/
def residueEffect (w : List α) (p : Fin n) (s : Finset (Event w)) : M :=
  φ ⟦project w (view d I w p \ s)⟧

/-- The table entry for a subset of indexed primary events. -/
def primaryEffect (w : List α) (p : Fin n) (R : Finset (Fin n)) : M :=
  residueEffect d φ w p (down I (primaryCut d I w p R))

omit [DecidableEq α] in
theorem residueEffect_inter (p : Fin n) (s : Finset (Event w)) :
    residueEffect d φ w p s = residueEffect d φ w p (view d I w p ∩ s) := by
  have he : view d I w p \ s = view d I w p \ (view d I w p ∩ s) := by
    ext e
    simp only [Finset.mem_sdiff, Finset.mem_inter]
    tauto
  unfold residueEffect
  rw [he]

omit [DecidableEq α] in
theorem process_residue_primary (hcompat : d.Compatible I) (p : Fin n)
    (P : Finset (Fin n)) :
    residueEffect d φ w p (jointView d I w P) =
      primaryEffect d φ w p (commonIndices d I w p P) := by
  rw [residueEffect_inter d φ p, view_inter_jointView d hcompat]
  rfl

theorem effect_union (s t : Finset (Event w)) (hs : IsIdeal I s) :
    φ ⟦project w (s ∪ t)⟧ = φ ⟦project w s⟧ * φ ⟦project w (t \ s)⟧ := by
  have h := ideal_factorization_effect φ s (s ∪ t) hs Finset.subset_union_left
  simpa only [Finset.union_sdiff_left] using h

/-- Compose process residues in a fixed order, excluding events already seen. -/
def residueProduct (w : List α) : List (Fin n) → Finset (Event w) → M
  | [], _ => 1
  | p :: ps, s => residueEffect d φ w p s * residueProduct w ps (s ∪ view d I w p)

/-- Corollary 1.29, in the process-residue form used on PDF page 24. -/
theorem residueProduct_factorization (ps : List (Fin n)) (s : Finset (Event w))
    (hs : IsIdeal I s) :
    φ ⟦project w (s ∪ jointView d I w ps.toFinset)⟧ =
      φ ⟦project w s⟧ * residueProduct d φ w ps s := by
  induction ps generalizing s with
  | nil => simp [residueProduct, jointView]
  | cons p ps ih =>
    have hsi := hs.union (isIdeal_view d p)
    have he := effect_union φ s (view d I w p) hs
    have hu : s ∪ jointView d I w (p :: ps).toFinset =
        (s ∪ view d I w p) ∪ jointView d I w ps.toFinset := by
      ext e
      simp [jointView]
    rw [hu, ih _ hsi, he, mul_assoc]
    rfl

omit [DecidableEq α] in
theorem jointView_univ : jointView d I w Finset.univ = Finset.univ := by
  ext e
  simp only [mem_jointView, Finset.mem_univ, true_and, iff_true]
  exact exists_view d e

/-- All process residues reconstruct the effect of the complete input trace. -/
theorem residueProduct_finRange : residueProduct d φ w (List.finRange n) ∅ = φ ⟦w⟧ := by
  have h := residueProduct_factorization d φ (w := w) (List.finRange n) ∅ isIdeal_empty
  have he : (List.finRange n).toFinset = Finset.univ := by ext p; simp
  simpa [he, jointView_univ, project_empty, project_univ] using h.symm

omit [DecidableEq α] in
/-- A recognizing morphism can be applied after composing the trace-valued residues. -/
theorem residueProduct_map (ps : List (Fin n)) (s : Finset (Event w)) :
    residueProduct d φ w ps s =
      φ (residueProduct d (MonoidHom.id (Trace I)) w ps s) := by
  induction ps generalizing s with
  | nil => simp [residueProduct]
  | cons p ps ih => simp only [residueProduct, ih, map_mul, residueEffect, MonoidHom.id_apply]

/-- The residue product also reconstructs a joint view after removing an initial ideal.
Cancellation takes place in the trace monoid, before applying the finite morphism. -/
theorem residueProduct_residual (ps : List (Fin n)) (s : Finset (Event w))
    (hs : IsIdeal I s) (hsub : s ⊆ jointView d I w ps.toFinset) :
    residueProduct d φ w ps s = φ ⟦project w (jointView d I w ps.toFinset \ s)⟧ := by
  rw [residueProduct_map]
  apply congrArg φ
  have hprod := residueProduct_factorization d (MonoidHom.id (Trace I)) ps s hs
  have hfactor := ideal_factorization_effect (MonoidHom.id (Trace I)) s
    (jointView d I w ps.toFinset) hs hsub
  simp only [MonoidHom.id_apply, Finset.union_eq_right.mpr hsub] at hprod hfactor
  exact @mul_left_cancel (Trace I) inferInstance inferInstance ⟦project w s⟧ _ _
    (hprod.symm.trans hfactor)

end
end TraceTheory.Zielonka
