import TraceTheory.Zielonka.Events
import Mathlib.Data.Finset.Max

namespace TraceTheory.Zielonka

open Classical

noncomputable section

variable {α : Type} {n : ℕ} {I : Independence α} {w : List α}

/-- The ideal generated by a set of events. -/
def down (I : Independence α) (s : Finset (Event w)) : Finset (Event w) :=
  Finset.univ.filter (fun e => ∃ f ∈ s, Before I w e f)

@[simp]
theorem mem_down (s : Finset (Event w)) (e : Event w) :
    e ∈ down I s ↔ ∃ f ∈ s, Before I w e f := by simp [down]

theorem subset_down (s : Finset (Event w)) : s ⊆ down I s :=
  fun e he => (mem_down s e).mpr ⟨e, he, before_refl e⟩

theorem isIdeal_down (s : Finset (Event w)) : IsIdeal I (down I s) := by
  intro e f hef hf
  obtain ⟨g, hg, hfg⟩ := (mem_down s f).mp hf
  exact (mem_down s e).mpr ⟨g, hg, hef.trans hfg⟩

@[simp]
theorem down_empty : down I (∅ : Finset (Event w)) = ∅ := by simp [down]

theorem down_union (s t : Finset (Event w)) : down I (s ∪ t) = down I s ∪ down I t := by
  ext e
  simp only [mem_down, Finset.mem_union]
  constructor
  · rintro ⟨f, hf | hf, hef⟩
    · exact .inl ⟨f, hf, hef⟩
    · exact .inr ⟨f, hf, hef⟩
  · rintro (⟨f, hf, hef⟩ | ⟨f, hf, hef⟩)
    · exact ⟨f, .inl hf, hef⟩
    · exact ⟨f, .inr hf, hef⟩

theorem IsIdeal.down_eq {s : Finset (Event w)} (hs : IsIdeal I s) : down I s = s := by
  apply Finset.Subset.antisymm _ (subset_down s)
  intro e he
  obtain ⟨f, hf, hef⟩ := (mem_down s e).mp he
  exact hs hef hf

variable (d : Distribution α n)

/-- The events in which a process participates. -/
def processEvents (w : List α) (p : Fin n) : Finset (Event w) :=
  Finset.univ.filter (fun e => p ∈ d.loc (label w e))

@[simp]
theorem mem_processEvents (p : Fin n) (e : Event w) :
    e ∈ processEvents d w p ↔ p ∈ d.loc (label w e) := by simp [processEvents]

/-- The process view is the causal past of all events involving that process. -/
def view (I : Independence α) (w : List α) (p : Fin n) : Finset (Event w) :=
  down I (processEvents d w p)

theorem isIdeal_view (p : Fin n) : IsIdeal I (view d I w p) := isIdeal_down _

@[simp]
theorem mem_view (p : Fin n) (e : Event w) :
    e ∈ view d I w p ↔ ∃ f, p ∈ d.loc (label w f) ∧ Before I w e f := by
  simp [view, mem_down]

theorem mem_view_of_participates (p : Fin n) (e : Event w)
    (hp : p ∈ d.loc (label w e)) : e ∈ view d I w p :=
  (mem_view d p e).mpr ⟨e, hp, before_refl e⟩

/-- Every real event is seen by at least one process. -/
theorem exists_view (e : Event w) : ∃ p, e ∈ view d I w p := by
  obtain ⟨p, hp⟩ := d.loc_nonempty (label w e)
  exact ⟨p, mem_view_of_participates d p e hp⟩

variable {d}

theorem before_of_same_process (hcompat : d.Compatible I) (p : Fin n)
    {e f : Event w} (he : p ∈ d.loc (label w e)) (hf : p ∈ d.loc (label w f))
    (hef : e ≤ f) : Before I w e f := by
  rcases lt_or_eq_of_le hef with hlt | rfl
  · apply before_of_lt_of_dependent hlt
    intro h
    exact Finset.disjoint_left.mp ((hcompat _ _).mp h) he hf
  · exact before_refl e

variable (d)

/-- Latest information in an ideal. `none` covers processes with no event yet. -/
def latest (s : Finset (Event w)) (p : Fin n) : Option (Event w) :=
  let es := s ∩ processEvents d w p
  if h : es.Nonempty then some (es.max' h) else none

theorem latest_eq_none_iff (s : Finset (Event w)) (p : Fin n) :
    latest d s p = none ↔ s ∩ processEvents d w p = ∅ := by
  simp [latest, Finset.not_nonempty_iff_eq_empty]

theorem latest_eq_some_iff (s : Finset (Event w)) (p : Fin n) (e : Event w) :
    latest d s p = some e ↔ e ∈ s ∧ p ∈ d.loc (label w e) ∧
      ∀ f ∈ s, p ∈ d.loc (label w f) → f ≤ e := by
  unfold latest
  dsimp only
  split_ifs with h
  · constructor
    · intro he
      obtain rfl := Option.some.inj he
      have hm := Finset.max'_mem _ h
      exact ⟨(Finset.mem_inter.mp hm).1,
        (mem_processEvents d _ _).mp (Finset.mem_inter.mp hm).2,
        fun f hf hp => Finset.le_max' _ f (Finset.mem_inter.mpr
          ⟨hf, (mem_processEvents d _ _).mpr hp⟩)⟩
    · intro ⟨he, hp, hmax⟩
      congr 1
      apply le_antisymm
      · have hm := Finset.max'_mem _ h
        exact hmax _ (Finset.mem_inter.mp hm).1
          ((mem_processEvents d _ _).mp (Finset.mem_inter.mp hm).2)
      · exact Finset.le_max' _ e (Finset.mem_inter.mpr
          ⟨he, (mem_processEvents d _ _).mpr hp⟩)
  · simp only [false_iff, not_and]
    intro he hp
    exact (h ⟨e, Finset.mem_inter.mpr ⟨he, (mem_processEvents d _ _).mpr hp⟩⟩).elim

/-- In an ideal, the latest process event causally dominates every other process event. -/
theorem before_latest (hcompat : d.Compatible I) (s : Finset (Event w)) (p : Fin n)
    {e f : Event w} (he : latest d s p = some e)
    (hf : f ∈ s) (hp : p ∈ d.loc (label w f)) : Before I w f e := by
  obtain ⟨_, hep, hmax⟩ := (latest_eq_some_iff d s p e).mp he
  exact before_of_same_process hcompat p hp hep (hmax f hf hp)

/-- A process view is generated by its last event, when it has one. -/
theorem view_eq_down_latest (hcompat : d.Compatible I) (p : Fin n) {e : Event w}
    (he : latest d Finset.univ p = some e) : view d I w p = down I {e} := by
  obtain ⟨_, hep, _⟩ := (latest_eq_some_iff d _ _ _).mp he
  ext f
  simp only [mem_view, mem_down, Finset.mem_singleton, exists_eq_left]
  constructor
  · rintro ⟨g, hgp, hfg⟩
    exact hfg.trans (before_latest d hcompat _ p he (Finset.mem_univ g) hgp)
  · intro hfe
    exact ⟨e, hep, hfe⟩

theorem view_eq_empty_of_latest_eq_none (p : Fin n)
    (he : latest d (Finset.univ : Finset (Event w)) p = none) : view d I w p = ∅ := by
  have h := (latest_eq_none_iff d _ _).mp he
  simp only [Finset.univ_inter] at h
  simp [view, h]

/-- Indexed primary information: the latest `q`-event known by `p`. -/
def primary (I : Independence α) (w : List α) (p q : Fin n) : Option (Event w) :=
  latest d (view d I w p) q

/-- Indexed secondary information: what `q` knew about `r` at the latest `q`-event known by `p`. -/
def secondary (I : Independence α) (w : List α) (p q r : Fin n) : Option (Event w) :=
  latest d (down I ((primary d I w p q).toFinset)) r

theorem primary_self (p : Fin n) : primary d I w p p = latest d Finset.univ p := by
  cases he : latest d (Finset.univ : Finset (Event w)) p with
  | none => simp [primary, view_eq_empty_of_latest_eq_none d p he, latest]
  | some e =>
    obtain ⟨_, hp, hmax⟩ := (latest_eq_some_iff d _ _ _).mp he
    apply (latest_eq_some_iff d _ _ _).mpr
    exact ⟨mem_view_of_participates d p e hp, hp, fun f _ hf => hmax f (Finset.mem_univ f) hf⟩

end

end TraceTheory.Zielonka
