import Mathlib.Algebra.FreeMonoid.Basic
import TraceTheory.List

variable {α : Type}

namespace TraceTheory

/-- A dependence is a finite, reflexive, and symmetric relation. -/
structure Dependence (α : Type) where
  /-- The dependence relation. -/
  rel : α → α → Prop
  refl : ∀ a, rel a a
  symm: ∀ a b, rel a b → rel b a

/-- An independence is a finite, irreflexive, and symmetric relation. -/
structure Independence (α : Type) where
  /-- The independence relation. -/
  rel : α → α → Prop
  irrefl : ∀ a, ¬ rel a a
  symm : ∀ a b, rel a b → rel b a

/-- The Independence relation induced by a Dependence `D`. -/
def inducedIndependence {α : Type} (D : Dependence α) : Independence α where
  rel := fun a b => ¬D.rel a b
  irrefl := by
    intro a h
    exact h (D.refl a)
  symm := by
    intro a b hab hba
    exact hab (D.symm b a hba)

/-- The trace equivalence relation is the least congruence $\equiv$ such that for all symbols
$a$ and $b$, $(a,b) \in I \leftrightarrow ab \equiv ba$.

Intuitively, two strings (lists of symbols) are equivalent if one can be transformed into the other
by a finite sequence of swaps of adjacent independent symbols.

The relation is inductively generated by:
- **Swap:** If `I.rel a b`, then `[a, b]` is equivalent to `[b, a]` (swapping adjacent independent
  symbols).
- **Reflexivity:** Every word is equivalent to itself.
- **Symmetry:** If `w₁` is equivalent to `w₂`, then `w₂` is equivalent to `w₁`.
- **Transitivity:** If `w₁` is equivalent to `w₂` and `w₂` is equivalent to `w₃`, then `w₁` is
  equivalent to `w₃`.
- **Compatibility:** If `w₁` is equivalent to `w₂` and `w₃` is equivalent to `w₄`, then `w₁ ++ w₃`
  is equivalent to `w₂ ++ w₄`. -/
inductive TraceEquiv (I : Independence α) : List α → List α → Prop
  | swap : ∀ a b, I.rel a b → TraceEquiv I [a, b] [b, a]
  | refl : ∀ w₁, TraceEquiv I w₁ w₁
  | symm : ∀ {w₁ w₂}, TraceEquiv I w₁ w₂ → TraceEquiv I w₂ w₁
  | trans : ∀ {w₁ w₂ w₃},
      TraceEquiv I w₁ w₂ →
      TraceEquiv I w₂ w₃ →
      TraceEquiv I w₁ w₃
  | compat : ∀ {w₁ w₂ w₃ w₄},
      TraceEquiv I w₁ w₂ →
      TraceEquiv I w₃ w₄ →
      TraceEquiv I (w₁ ++ w₃) (w₂ ++ w₄)

theorem TraceEquiv.context {u v : List α} (l r : List α) (h : TraceEquiv I u v) :
    TraceEquiv I (l ++ u ++ r) (l ++ v ++ r) :=
  TraceEquiv.compat (TraceEquiv.compat (TraceEquiv.refl l) h) (TraceEquiv.refl r)

/-- The binary relation $~$ such that $u~v$ if and only if there exists strings $x,y$ and symbols
$a,b$ such that $u=xaby$ and $v=xbay$. -/
inductive CommuteOnce (I : Independence α) : List α → List α → Prop
  | mk : ∀ (x y : List α) (a b : α), I.rel a b →
    CommuteOnce I (x ++ [a, b] ++ y) (x ++ [b, a] ++ y)

variable {I : Independence α}

lemma eqvGen_append_right {u v w : List α}
    (h : Relation.EqvGen (CommuteOnce I) u v) :
    Relation.EqvGen (CommuteOnce I) (u ++ w) (v ++ w) := by
  induction h with
  | rel x y h_comm =>
    apply Relation.EqvGen.rel
    rcases h_comm with ⟨x', y', a, b, h_indep⟩
    simpa using CommuteOnce.mk x' (y' ++ w) a b h_indep
  | refl _ =>
    apply Relation.EqvGen.refl
  | symm _ _ _ ih =>
    apply Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ =>
    apply Relation.EqvGen.trans _ _ _ ih₁ ih₂

lemma eqvGen_append_left {u v w : List α}
    (h : Relation.EqvGen (CommuteOnce I) u v) :
    Relation.EqvGen (CommuteOnce I) (w ++ u) (w ++ v) := by
  induction h with
  | rel x y h_comm =>
    apply Relation.EqvGen.rel
    rcases h_comm with ⟨x', y', a, b, h_indep⟩
    simpa using CommuteOnce.mk (w ++ x') y' a b h_indep
  | refl _ =>
    apply Relation.EqvGen.refl
  | symm _ _ _ ih =>
    apply Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ =>
    apply Relation.EqvGen.trans _ _ _ ih₁ ih₂

/-- Trace equivalence is the equivalence closure of $~$. -/
theorem traceEquiv_iff_eqvGen_commuteOnce (u v : List α) :
    TraceEquiv I u v ↔ Relation.EqvGen (CommuteOnce I) u v := by
  constructor
  · intro h
    induction h with
    | swap a b h_indep =>
      apply Relation.EqvGen.rel
      simpa using CommuteOnce.mk [] [] a b h_indep
    | refl _ =>
      apply Relation.EqvGen.refl
    | symm _ ih =>
      apply Relation.EqvGen.symm _ _ ih
    | trans _ _ ih₁ ih₂ =>
      apply Relation.EqvGen.trans _ _ _ ih₁ ih₂
    | compat _ _ ih₁ ih₂ =>
      expose_names
      apply Relation.EqvGen.trans (w₁ ++ w₃) (w₂ ++ w₃) (w₂ ++ w₄)
      · apply eqvGen_append_right ih₁
      · apply eqvGen_append_left ih₂
  · intro h
    induction h with
    | rel x y h_comm =>
      rcases h_comm with ⟨x', y', a, b, h_indep⟩
      apply TraceEquiv.context
      exact TraceEquiv.swap a b h_indep
    | refl _ =>
      apply TraceEquiv.refl
    | symm _ _ _ ih =>
      apply TraceEquiv.symm ih
    | trans _ _ _ _ _ ih1 ih2 =>
      apply TraceEquiv.trans ih1 ih2

theorem length_eq_of_equiv {u v : List α} (h : TraceEquiv I u v) :
    u.length = v.length := by
  induction h with
  | swap _ _ _ =>
    rfl
  | refl _ =>
    rfl
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp [ih₁, ih₂]

theorem mem_iff_mem {u v : List α} (a : α) (h : TraceEquiv I u v) :
    (a ∈ u ↔ a ∈ v) := by
  induction h with
  | swap _ _ _ =>
    simp
    exact Or.comm
  | refl _ =>
    exact Eq.to_iff rfl
  | symm _ ih =>
    exact Iff.symm ih
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact or_congr ih₁ ih₂

/-- The mirror rule. -/
theorem reverse_equiv_of_equiv {u v : List α} (h : TraceEquiv I u v) :
    TraceEquiv I u.reverse v.reverse := by
  induction h with
  | swap a b h =>
    simp
    exact TraceEquiv.swap b a (I.symm a b h)
  | refl u' =>
    exact TraceEquiv.refl u'.reverse
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact ih₂.compat ih₁

/-- The projection rule. -/
theorem proj_equiv_of_equiv {u v : List α} {S : Finset α} [DecidableEq α] (h : TraceEquiv I u v) :
    TraceEquiv I (proj S u) (proj S v) := by
  induction h with
  | swap a b h_indep =>
    by_cases ha : a ∈ S <;> by_cases hb : b ∈ S <;> simp [proj, ha, hb]
    · apply TraceEquiv.swap
      exact h_indep
    · apply TraceEquiv.refl
    · apply TraceEquiv.refl
    · apply TraceEquiv.refl
  | refl _ =>
    apply TraceEquiv.refl
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact ih₁.compat ih₂

theorem proj_eq_of_equiv {u v : List α} [DecidableEq α]
    (D : Dependence α) (h : TraceEquiv (inducedIndependence D) u v)
    (a b : α) (h_dep : D.rel a b) :
    proj {a, b} u = proj {a, b} v := by
  induction h with
  | swap a' b' h_indep =>
    dsimp [proj]
    by_cases ha' : a' ∈ ({a, b} : Finset α) <;> by_cases hb' : b' ∈ ({a, b} : Finset α)
    · have h_dep : D.rel a' b' := by
        simp at ha' hb'
        rcases ha' with rfl | rfl <;> rcases hb' with rfl | rfl
        · apply D.refl
        · exact h_dep
        · exact D.symm b' a' h_dep
        · apply D.refl
      dsimp [inducedIndependence] at h_indep
      contradiction
    · simp [List.filter, ha', hb']
    · simp [List.filter, ha', hb']
    · simp [List.filter, ha', hb']
  | refl _ =>
    rfl
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp [proj_append]
    rw [ih₁, ih₂]

theorem cancelRight_congr {u v : List α} [DecidableEq α] (a : α) (h : TraceEquiv I u v) :
    TraceEquiv I (u ÷ a) (v ÷ a) := by
  induction h with
  | swap b c h_indep =>
    by_cases hab : b = a <;> by_cases hac : c = a
    · subst hab hac
      apply TraceEquiv.refl
    · simp [cancelRight, hab, hac]
      apply TraceEquiv.refl
    · simp [cancelRight, hab, hac]
      apply TraceEquiv.refl
    · simp [cancelRight, hab, hac]
      apply TraceEquiv.swap
      exact h_indep
  | refl _ =>
    apply TraceEquiv.refl
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat t₁ t₂ ih₁ ih₂ =>
    expose_names
    by_cases h_mem : a ∈ w₃
    · simp [h_mem, (mem_iff_mem a t₂).mp h_mem]
      exact t₁.compat ih₂
    · simp [h_mem, (mem_iff_mem a t₂).mpr.mt h_mem]
      exact ih₁.compat t₂

theorem erase_congr {u v : List α} [DecidableEq α] (a : α) (h : TraceEquiv I u v) :
    TraceEquiv I (u.erase a) (v.erase a) := by
  have h_erase (w : List α) : w.erase a = (w.reverse ÷ a).reverse := by simp [cancelRight]
  simp [h_erase]
  apply reverse_equiv_of_equiv
  apply cancelRight_congr
  apply reverse_equiv_of_equiv
  exact h

theorem append_cancel_left {w u v : List α} [DecidableEq α] (h : TraceEquiv I (w ++ u) (w ++ v)) :
    TraceEquiv I u v := by
  induction w with
  | nil =>
    simpa
  | cons a w' ih =>
    replace h := erase_congr a h
    simp at h
    exact ih h

theorem append_cancel_right {w u v : List α} [DecidableEq α] (h : TraceEquiv I (u ++ w) (v ++ w)) :
    TraceEquiv I u v := by
  replace h := reverse_equiv_of_equiv h
  simp only [List.reverse_append] at h
  replace h := reverse_equiv_of_equiv (append_cancel_left h)
  simp only [List.reverse_reverse] at h
  exact h

theorem append_cancel_middle {l r u v : List α} [DecidableEq α]
    (h : TraceEquiv I (l ++ u ++ r) (l ++ v ++ r)) :
    TraceEquiv I u v := by
  have h_left := append_cancel_right h
  exact append_cancel_left h_left

lemma equiv_length_eq_two {a b : α} {w : List α} (h : TraceEquiv I [a, b] w) :
    w = [a, b] ∨ w = [b, a] := by
  rcases List.length_eq_two.mp (length_eq_of_equiv h).symm with ⟨c, d, hw⟩
  subst hw
  by_cases heq : a = b
  · subst heq
    have hc : c = a := by simpa using (mem_iff_mem c h.symm).mp
    have hd : d = a := by simpa using (mem_iff_mem d h.symm).mp
    simp [hc, hd]
  · have ha : a = c ∨ a = d := by simpa using (mem_iff_mem a h).mp
    have hb : b = c ∨ b = d := by simpa using (mem_iff_mem b h).mp
    rcases ha with hac | had <;> rcases hb with hbc | hbd
    · subst hbc
      contradiction
    · left
      simp [hac, hbd]
    · right
      simp [had, hbc]
    · subst hbd
      contradiction

lemma equiv_singletons {a b : α} (h : TraceEquiv I [a] [b]) : a = b := by
  generalize hu : ([a] : List α) = u at h
  generalize hv : ([b] : List α) = v at h
  induction h generalizing a b with
  | swap _ _ _ =>
    cases hu
  | refl _ =>
    subst hv
    injection hu
  | symm _ ih =>
    exact (ih hv hu).symm
  | trans t₁ t₂ _ _ =>
    have ht₁ := mem_iff_mem a t₁
    have ht₂ := mem_iff_mem a t₂
    have h_trans := ht₁.trans ht₂
    subst hu hv
    simpa using h_trans
  | compat t₁ t₂ ih₁ ih₂ =>
    rcases List.singleton_eq_append_iff.mp hu with ⟨hw₁, hw₃⟩ | ⟨hw₁, hw₃⟩
    <;> rcases List.singleton_eq_append_iff.mp hv with ⟨hw₂, hw₄⟩ | ⟨hw₂, hw₄⟩
    · exact ih₂ hw₃.symm hw₄.symm
    · have ht₁ := length_eq_of_equiv t₁
      subst hw₁ hw₂
      contradiction
    · have ht₁ := length_eq_of_equiv t₁
      subst hw₁ hw₂
      contradiction
    · exact ih₁ hw₁.symm hw₂.symm

theorem indep_of_comm_equiv_of_ne {a b : α} (h : TraceEquiv I [a, b] [b, a]) (hne : a ≠ b) :
    I.rel a b := by
  generalize hu : [a, b] = u at h
  generalize hv : [b, a] = v at h
  induction h generalizing a b with
  | swap c d h_rel =>
    injection hu with ha
    injection hv with hb
    subst ha hb
    exact h_rel
  | refl _ =>
    cases hu.trans hv.symm
    contradiction
  | symm _ ih =>
    exact I.symm b a (ih (hne.symm) hv hu)
  | trans t₁ _ ih₁ ih₂ =>
    expose_names
    rw [← hu] at t₁
    rcases equiv_length_eq_two t₁ with h₁ | h₂
    · exact ih₂ hne h₁.symm hv
    · exact ih₁ hne hu h₂.symm
  | compat t₁ t₂ ih₁ ih₂ =>
    expose_names
    have h₁ : w₁.length + w₃.length = 2 := by simp [← List.length_append, ← hu]
    have h₂ : w₂.length + w₄.length = 2 := by simp [← List.length_append, ← hv]
    have ht₁ := length_eq_of_equiv t₁
    have ht₂ := length_eq_of_equiv t₂
    rcases Nat.add_eq_two_iff.mp h₁ with ⟨hw₁, hw₃⟩ | ⟨hw₁, hw₃⟩ | ⟨hw₁, hw₃⟩
    <;> rcases Nat.add_eq_two_iff.mp h₂ with ⟨hw₂, hw₄⟩ | ⟨hw₂, hw₄⟩ | ⟨hw₂, hw₄⟩
    · rw [List.length_eq_zero_iff.mp hw₁, List.nil_append] at hu
      rw [List.length_eq_zero_iff.mp hw₂, List.nil_append] at hv
      exact ih₂ hne hu hv
    · rw [hw₁, hw₂] at ht₁
      contradiction
    . rw [hw₁, hw₂] at ht₁
      contradiction
    · rw [hw₁, hw₂] at ht₁
      contradiction
    · rcases List.length_eq_one_iff.mp hw₁ with ⟨c, hc⟩
      rcases List.length_eq_one_iff.mp hw₂ with ⟨d, hd⟩
      subst hc hd
      have heq : c = d := equiv_singletons t₁
      simp at hu hv
      rw [← hu.left, ← hv.left] at heq
      contradiction
    · rw [hw₁, hw₂] at ht₁
      contradiction
    · rw [hw₁, hw₂] at ht₁
      contradiction
    · rw [hw₁, hw₂] at ht₁
      contradiction
    · rw [List.length_eq_zero_iff.mp hw₃, List.append_nil] at hu
      rw [List.length_eq_zero_iff.mp hw₄, List.append_nil] at hv
      exact ih₁ hne hu hv

theorem indep_and_exists_of_equiv_of_tail_ne {u v : List α} {a b : α} [DecidableEq α]
    (h : TraceEquiv I (u ++ [a]) (v ++ [b]))
    (hne : a ≠ b) :
    I.rel a b ∧
    ∃ w, TraceEquiv I u (w ++ [b]) ∧ TraceEquiv I v (w ++ [a]) := by
  have h_cancel_a := by simpa [hne] using cancelRight_congr a h
  have h_cancel_b := by simpa [hne.symm] using (cancelRight_congr b h).symm
  have h_cancel_ab := by simpa [hne] using cancelRight_congr b h_cancel_a
  have h_cancel_b_concat_b := h_cancel_a.trans (h_cancel_ab.compat (TraceEquiv.refl [b])).symm
  have h_cancel_b_concat_ba := h_cancel_b_concat_b.compat (TraceEquiv.refl [a])
  have h_cancel_b_concat_ab := h_cancel_b.compat (TraceEquiv.refl [b])
  have h_tail := by simpa using h_cancel_b_concat_ab.symm.trans (h.symm.trans h_cancel_b_concat_ba)
  have h_ab_ba := append_cancel_left h_tail
  exact ⟨indep_of_comm_equiv_of_ne h_ab_ba hne, u ÷ b, h_cancel_b_concat_b, h_cancel_b⟩

/-- Strings $u,v$ are independent if every symbol in $u$ is independent of every symbol in $v$. -/
@[simp]
def independent (I : Independence α) (u v : List α) := ∀ a ∈ u, ∀ b ∈ v, I.rel a b

theorem independent_symm {u v : List α} (h : independent I u v) :
    independent I v u := by
  intro a ha b hb
  exact I.symm b a (h b hb a ha)

theorem indep_of_comm_singleton {u v w : List α} {a : α} [DecidableEq α]
    (h : TraceEquiv I (u ++ [a] ++ v) (w ++ [a])) (h_mem : a ∉ v) :
    independent I [a] v := by
  induction v using List.reverseRecOn generalizing w with
  | nil =>
    simp
  | append_singleton x b ih =>
    intro a' ha' b' hb'
    simp at ha' hb' h_mem
    subst ha'
    rcases h_mem with ⟨h_mem', hne⟩
    rw [eq_comm] at hne
    rw [← List.append_assoc] at h
    have hr := (indep_and_exists_of_equiv_of_tail_ne h hne).left
    replace h := cancelRight_congr b h
    replace h := by simpa only [append_singleton_cancelRight, Ne.symm hne, ↓reduceIte] using h
    replace h := by simpa using ih h h_mem'
    rcases hb' with h₁ | h₂
    · exact h b' h₁
    · subst h₂
      exact I.symm b' a' hr

theorem comm_singleton_of_indep {w : List α} {a : α} (h : independent I [a] w) :
    TraceEquiv I (w ++ [a]) ([a] ++ w) := by
  induction w using List.reverseRecOn with
  | nil =>
    apply TraceEquiv.refl
  | append_singleton w' b ih =>
    simp at h
    have haw' : independent I [a] w' := by
      intro a' ha' b' hb'
      simp at ha'
      subst ha'
      exact h b' (Or.intro_left (b' = b) hb')
    have ht := ih haw'
    have hb := ht.compat (TraceEquiv.refl [b])
    have hab : TraceEquiv I (w' ++ [b] ++ [a]) (w' ++ [a] ++ [b]) := by
      have hr := h b
      simp at hr ⊢
      exact (TraceEquiv.refl w').compat (TraceEquiv.swap b a (I.symm a b hr))
    exact hab.trans hb

theorem indep_of_indep_of_equiv {u v w: List α}
    (h : independent I u v) (ht : TraceEquiv I v w) :
    independent I u w := by
  intro a ha b hb
  have h_alph := mem_iff_mem b ht
  have h_mem := h_alph.mpr hb
  exact h a ha b h_mem

theorem indep_of_indep_append_right {u v w: List α} (h : independent I w (u ++ v)) :
    independent I w u ∧ independent I w v := by
  constructor
  · intro a ha b hb
    apply h
    apply ha
    apply List.mem_append.mpr
    left
    exact hb
  · intro a ha b hb
    apply h
    apply ha
    apply List.mem_append.mpr
    right
    exact hb

theorem levi_lemma {u v x y : List α} [DecidableEq α] (h : TraceEquiv I (u ++ v) (x ++ y)) :
    ∃ z₁ z₂ z₃ z₄, independent I z₂ z₃
    ∧ TraceEquiv I u (z₁ ++ z₂) ∧ TraceEquiv I v (z₃ ++ z₄)
    ∧ TraceEquiv I x (z₁ ++ z₃) ∧ TraceEquiv I y (z₂ ++ z₄) := by
  induction y using List.reverseRecOn generalizing u v with
  | nil =>
    use u, [], v, []
    simp [TraceEquiv.refl] at *
    exact h.symm
  | append_singleton w e ih =>
    by_cases hev : e ∈ v
    · have ⟨v', v'', hv, hv''⟩ := rightmost_occurrence hev
      have h_cancel := cancelRight_congr e h
      subst hv
      simp only [append_cancelRight] at h_cancel
      simp [hv''] at h_cancel
      have ⟨z₁', z₂', z₃', z₄', h_indep, ht₁, ht₂, ht₃, ht₄⟩ := ih h_cancel
      use z₁', z₂', z₃', z₄' ++ [e], h_indep
      replace ht₄ := ht₄.compat (TraceEquiv.refl [e])
      have he : TraceEquiv I (v'' ++ [e]) ([e] ++ v'') := by
        simp [← List.append_assoc] at h
        exact comm_singleton_of_indep (indep_of_comm_singleton h hv'')
      have hv'e := TraceEquiv.symm ((TraceEquiv.refl v').compat he)
      simp only [← List.append_assoc] at hv'e ⊢
      replace ht₂ := hv'e.trans (ht₂.compat (TraceEquiv.refl [e]))
      exact ⟨ht₁, ht₂, ht₃, ht₄⟩
    · have heu : e ∈ u := by
        have h_alph := by simpa using mem_iff_mem e h
        exact Or.resolve_right h_alph hev
      have ⟨u', u'', hu, hu''⟩ := rightmost_occurrence heu
      have h_cancel := cancelRight_congr e h
      subst hu
      simp only [append_cancelRight] at h_cancel
      simp [hev, hu''] at h_cancel
      rw [← List.append_assoc] at h_cancel
      have ⟨z₁', z₂', z₃', z₄', h_indep, ht₁, ht₂, ht₃, ht₄⟩ := ih h_cancel
      have h_indep' : independent I [e] (u'' ++ v) := by
        rw [← List.append_assoc, List.append_assoc] at h
        exact indep_of_comm_singleton h (List.not_mem_append hu'' hev)
      replace h_indep : independent I (z₂' ++ [e]) z₃' := by
        intro a ha b hb
        simp at ha
        rcases ha with h₁ | h₂
        · exact h_indep a h₁ b hb
        · subst h₂
          have h_indep'' := indep_of_indep_of_equiv (indep_of_indep_append_right h_indep').right ht₂
          simp at h_indep''
          exact h_indep'' b (Or.inl hb)
      use z₁', z₂' ++ [e], z₃', z₄', h_indep
      have heu'' : TraceEquiv I (u'' ++ [e]) ([e] ++ u'') :=
        comm_singleton_of_indep (indep_of_indep_append_right h_indep').left
      have hu'e := TraceEquiv.symm ((TraceEquiv.refl u').compat heu'')
      simp only [← List.append_assoc] at hu'e
      replace ht₁ := hu'e.trans (ht₁.compat (TraceEquiv.refl [e]))
      have hez₄' : TraceEquiv I (z₄' ++ [e]) ([e] ++ z₄') := by
        have h_indep'' := indep_of_indep_of_equiv (indep_of_indep_append_right h_indep').right ht₂
        exact comm_singleton_of_indep (indep_of_indep_append_right h_indep'').right
      have hz₂'e := (TraceEquiv.refl z₂').compat hez₄'
      simp only [← List.append_assoc] at hz₂'e ⊢
      replace ht₄ := (ht₄.compat (TraceEquiv.refl [e])).trans hz₂'e
      exact ⟨ht₁, ht₂, ht₃, ht₄⟩

theorem projection_lemma {u v : List α} [DecidableEq α] (D : Dependence α) :
    TraceEquiv (inducedIndependence D) u v ↔
    ∀ a b, D.rel a b → proj {a, b} u = proj {a, b} v := by
  constructor
  · apply proj_eq_of_equiv
  · intro h
    induction u using List.reverseRecOn generalizing v with
    | nil =>
      have hv : v = [] := by
        have h_symb : ∀ x, proj {x, x} [] = proj {x, x} v := fun x => h x x (D.refl x)
        dsimp [proj] at h_symb
        cases v with
        | nil =>
          rfl
        | cons c _ =>
          have h_absurd := h_symb c
          simp at h_absurd
      subst hv
      apply TraceEquiv.refl
    | append_singleton u' c ih =>
      have hv : c ∈ v := by
        have hc := h c c (D.refl c)
        simp [proj] at hc
        apply List.mem_of_mem_filter
        rw [← hc]
        simp
      have ⟨v', v'', heq, hc⟩ := rightmost_occurrence hv
      have h_indep : independent (inducedIndependence D) [c] v'' := by
        intro c hc b hb
        simp at hc
        subst hc
        dsimp [inducedIndependence]
        by_cases h_dep : D.rel c b
        · have hc' := h c b h_dep
          rw [heq] at hc'
          dsimp [proj] at hc'
          simp only [List.filter_append] at hc'
          have hv''_nonempty : v''.filter (· ∈ ({c, b} : Finset α)) ≠ [] := by
            intro h_empty
            have h_b_in : b ∈ v''.filter (· ∈ ({c, b} : Finset α)) := by
              rw [List.mem_filter]
              simp [hb]
            rw [h_empty] at h_b_in
            contradiction
          have h_lhs_end :
              (u'.filter (· ∈ ({c, b} : Finset α)) ++
              [c].filter (· ∈ ({c, b} : Finset α))).getLast? = some c := by
            simp
          have h_rhs_end :
              (v'.filter (· ∈ ({c, b} : Finset α)) ++
              [c].filter (· ∈ ({c, b} : Finset α)) ++
              v''.filter (· ∈ ({c, b} : Finset α))).getLast?
              = (v''.filter (· ∈ ({c, b} : Finset α))).getLast? := by
            exact List.getLast?_append_of_ne_nil _ hv''_nonempty
          rw [← hc', h_lhs_end] at h_rhs_end
          have h_absurd : c ∈ v'' := by
            have h_mem := List.mem_of_getLast? h_rhs_end.symm
            simp at h_mem
            exact h_mem
          contradiction
        · exact h_dep
      have h_comm : TraceEquiv (inducedIndependence D) v (v' ++ v'' ++ [c]) := by
        rw [heq, List.append_assoc, List.append_assoc]
        apply TraceEquiv.compat (TraceEquiv.refl v')
        apply TraceEquiv.symm
        apply comm_singleton_of_indep
        exact h_indep
      apply TraceEquiv.symm
      apply TraceEquiv.trans h_comm
      refine TraceEquiv.compat ?_ (TraceEquiv.refl [c])
      apply TraceEquiv.symm
      apply ih
      intro a b h_dep
      have h_proj := h a b h_dep
      rw [heq] at h_proj
      dsimp [proj]
      by_cases hc_in : c ∈ ({a, b} : Finset α)
      · have hw''_empty : v''.filter (· ∈ ({a, b} : Finset α)) = [] := by
          apply List.filter_eq_nil_iff.mpr
          intro c' hc'
          simp at hc_in ⊢
          have hc'_indep := h_indep c (List.mem_singleton_self c) c' hc'
          rcases hc_in with rfl | rfl <;> constructor <;> intro hc'_eq <;> subst hc'_eq
          · exact (inducedIndependence D).irrefl c' hc'_indep
          · exact hc'_indep h_dep
          · exact hc'_indep (D.symm c' c h_dep)
          · exact (inducedIndependence D).irrefl c' hc'_indep
        dsimp [proj] at h_proj
        rw [List.filter_append, hw''_empty, List.append_nil]
        nth_rw 2 [List.filter_append] at h_proj
        rw [hw''_empty, List.append_nil, List.filter_append, List.filter_append] at h_proj
        exact List.append_cancel_right h_proj
      · simp at hc_in
        simp [proj, List.filter_append, hc_in] at h_proj
        simp
        exact h_proj

/-- The setoid structure on strings defined by the trace equivalence relation `TraceEquiv I`.
This serves as the basis for constructing the quotient type `Trace`. -/
def traceSetoid (I : Independence α) : Setoid (List α) where
  r := TraceEquiv I
  iseqv := Equivalence.mk TraceEquiv.refl TraceEquiv.symm TraceEquiv.trans

/-- The type of Mazurkiewicz traces, defined as the quotient of the free monoid
by the trace equivalence relation induced by `I`. -/
def Trace (I : Independence α) := Quotient (traceSetoid I)

/-- Composition (concatenation) of traces. This is induced by the concatenation
operation on the underlying strings. -/
@[simp]
def mul : Trace I -> Trace I -> Trace I := by
  exact Quotient.lift₂
    (fun w₁ w₂ => ⟦w₁ ++ w₂⟧)
    (by
      intro a₁ b₁ a₂ b₂ ha hb
      apply Quotient.sound
      exact ha.compat hb
    )

/-- The empty trace, represented by the equivalence class of the empty list. -/
def one := Quotient.mk (traceSetoid I) []

instance : Monoid (Trace I) where
  mul := mul
  one := one
  mul_assoc := by
    intro t₁ t₂ t₃
    refine Quotient.inductionOn₃ t₁ t₂ t₃ (fun w₁ w₂ w₃ => ?_)
    apply Quotient.sound
    rw [List.append_assoc]
    exact TraceEquiv.refl _
  one_mul := by
    intro t
    refine Quotient.inductionOn t (fun w => ?_)
    apply Quotient.sound
    rw [List.nil_append]
    exact TraceEquiv.refl _
  mul_one := by
    intro t
    refine Quotient.inductionOn t (fun w => ?_)
    apply Quotient.sound
    rw [List.append_nil]
    exact TraceEquiv.refl _

variable (I) in
/-- The prefix relation on traces. A trace `t₁` is a prefix of `t₂` if there exists
a trace `⟦w⟧` such that `t₁` concatenated with `⟦w⟧` equals `t₂`. -/
def isPrefix (t₁ t₂ : Trace I) := ∃ w, mul t₁ ⟦w⟧ = t₂

theorem exists_gcp {u v w : List α} [DecidableEq α]
    (hu : isPrefix I ⟦u⟧ ⟦w⟧) (hv : isPrefix I ⟦v⟧ ⟦w⟧) :
    ∃ g, isPrefix I ⟦g⟧ ⟦u⟧ ∧ isPrefix I ⟦g⟧ ⟦v⟧
    ∧ (∀ g', isPrefix I ⟦g'⟧ ⟦u⟧ → isPrefix I ⟦g'⟧ ⟦v⟧ → isPrefix I ⟦g'⟧ ⟦g⟧) := by
  have ⟨u', hu'⟩ := hu
  have ⟨v', hv'⟩ := hv
  simp at hu' hv'
  replace hu' := Quotient.exact hu'
  replace hv' := Quotient.exact hv'
  have ⟨z₁, z₂, z₃, _, h_indep, huz, _, hvz, _⟩ := levi_lemma (hu'.trans hv'.symm)
  use z₁
  and_intros
  · use z₂
    apply Quotient.sound
    exact huz.symm
  · use z₃
    apply Quotient.sound
    exact hvz.symm
  · intro g' hg'u hg'v
    have ⟨w₁, hw₁⟩ := hg'u
    have ⟨w₂, hw₂⟩ := hg'v
    replace hw₁ := Quotient.exact hw₁
    replace hw₂ := Quotient.exact hw₂
    replace hw₁ := hw₁.trans huz
    replace hw₂ := hw₂.trans hvz
    have ⟨y₁, y₂, y₃, y₄, h_indep_yy, hy_g', _, hy_z₁, hy_z₂⟩ := levi_lemma hw₁
    have h_y₂_empty : y₂ = [] := by
      have hyw : TraceEquiv I (y₂ ++ w₂) (y₃ ++ z₃) := by
        have hywz := (hy_g'.compat (TraceEquiv.refl w₂)).symm.trans hw₂
        replace hywz := (hywz.trans (hy_z₁.compat (TraceEquiv.refl z₃)))
        rw [List.append_assoc, List.append_assoc] at hywz
        exact append_cancel_left hywz
      by_cases he : y₂ = []
      · exact he
      · exfalso
        let ⟨a, ha⟩ := List.exists_mem_of_ne_nil y₂ he
        have ha_z₂ := (mem_iff_mem a hy_z₂).mpr (List.mem_append.mpr (Or.inl ha))
        have ha_yz := (mem_iff_mem a hyw).mp (List.mem_append.mpr (Or.inl ha))
        simp only [List.mem_append] at ha_yz
        have ha_y₃ : a ∈ y₃ := by
          rcases ha_yz with hay | haz
          · exact hay
          · exfalso
            exact I.irrefl a (h_indep a ha_z₂ a haz)
        exact I.irrefl a (h_indep_yy a ha a ha_y₃)
    rw [h_y₂_empty, List.append_nil] at hy_g'
    use y₃
    apply Quotient.sound
    exact (hy_g'.compat (TraceEquiv.refl y₃)).trans hy_z₁.symm

theorem comm_append_of_indep {w₁ w₂ : List α} (h : independent I w₁ w₂) :
    TraceEquiv I (w₁ ++ w₂) (w₂ ++ w₁) := by
  induction w₁ using List.reverseRecOn with
  | nil =>
    rw [List.nil_append, List.append_nil]
    exact TraceEquiv.refl _
  | append_singleton w' a ih =>
    replace h := indep_of_indep_append_right (independent_symm h)
    have ha := comm_singleton_of_indep (independent_symm h.right)
    have hw'a := ((TraceEquiv.refl w').compat ha).symm
    rw [← List.append_assoc, ← List.append_assoc] at hw'a
    apply hw'a.trans
    rw [← List.append_assoc]
    exact (ih (independent_symm h.left)).compat (TraceEquiv.refl [a])

theorem exists_lcd {u v w : List α} [DecidableEq α]
    (hu : isPrefix I ⟦u⟧ ⟦w⟧) (hv : isPrefix I ⟦v⟧ ⟦w⟧) :
    ∃ d, isPrefix I ⟦u⟧ ⟦d⟧ ∧ isPrefix I ⟦v⟧ ⟦d⟧
    ∧ (∀ d', isPrefix I ⟦u⟧ ⟦d'⟧ → isPrefix I ⟦v⟧ ⟦d'⟧ → isPrefix I ⟦d⟧ ⟦d'⟧) := by
  have ⟨u', hu'⟩ := hu
  have ⟨v', hv'⟩ := hv
  simp at hu' hv'
  replace hu' := Quotient.exact hu'
  replace hv' := Quotient.exact hv'
  have ⟨z₁, z₂, z₃, z₄, h_indep, huz, hu'z, hvz, hv'z⟩ := levi_lemma (hu'.trans hv'.symm)
  use z₁ ++ z₂ ++ z₃
  and_intros
  · use z₃
    apply Quotient.sound
    exact huz.compat (TraceEquiv.refl z₃)
  · use z₂
    apply Quotient.sound
    have hz := ((TraceEquiv.refl z₁).compat (comm_append_of_indep h_indep)).symm
    rw [← List.append_assoc, ← List.append_assoc] at hz
    apply (hvz.compat (TraceEquiv.refl z₂)).trans
    exact hz
  · intro d' hud' hvd'
    have ⟨w₁, hw₁⟩ := hud'
    have ⟨w₂, hw₂⟩ := hvd'
    replace hw₁ := Quotient.exact hw₁
    replace hw₂ := Quotient.exact hw₂
    have huv : TraceEquiv I (u ++ w₁) (v ++ w₂) := hw₁.trans hw₂.symm
    have hzw : TraceEquiv I (z₂ ++ w₁) (z₃ ++ w₂) := by
      have huzw := huz.compat (TraceEquiv.refl w₁)
      have hvzw := hvz.compat (TraceEquiv.refl w₂)
      have huvzw := huzw.symm.trans (huv.trans hvzw)
      rw [List.append_assoc, List.append_assoc] at huvzw
      exact append_cancel_left huvzw
    have ⟨y₁, y₂, y₃, y₄, _, hy_z₂, hy_w₁, hy_z₃, _⟩ := levi_lemma hzw
    have h_y₁_empty : y₁ = [] := by
      have h_indep_yy : independent I (y₁ ++ y₂) (y₁ ++ y₃) := by
        intro a ha b hb
        exact h_indep a ((mem_iff_mem a hy_z₂).mpr ha) b ((mem_iff_mem b hy_z₃).mpr hb)
      by_cases he : y₁ = []
      · exact he
      · exfalso
        let ⟨a, ha⟩ := List.exists_mem_of_ne_nil y₁ he
        have ha_left : a ∈ y₁ ++ y₂ := List.mem_append.mpr (Or.inl ha)
        have ha_right : a ∈ y₁ ++ y₃ := List.mem_append.mpr (Or.inl ha)
        have h_rel := h_indep_yy a ha_left a ha_right
        exact I.irrefl a h_rel
    rw [h_y₁_empty, List.nil_append] at hy_z₂ hy_z₃
    have hd' := hw₁.symm.trans (huz.compat (TraceEquiv.refl w₁))
    replace hd' := hd'.trans ((TraceEquiv.refl (z₁ ++ z₂)).compat hy_w₁)
    replace hd' :=
      hd'.trans ((TraceEquiv.refl (z₁ ++ z₂)).compat (hy_z₃.symm.compat (TraceEquiv.refl y₄)))
    rw [← List.append_assoc] at hd'
    use y₄
    apply Quotient.sound
    exact hd'.symm

instance : Monoid (List α) where
  one := []
  mul := List.append
  mul_assoc := List.append_assoc
  mul_one := List.append_nil
  one_mul := List.nil_append

variable [DecidableEq α]

variable (I) in
/-- A dependence morphism is any homomophism from the free monoid of strings onto another monoid
such that:

- $\phi(w)=\phi(\epsilon) \implies w = \epsilon$
- $(a,b)\in I \implies \phi(ab)=\phi(ba)$
- $\phi(ua)=\phi(v) \implies \phi(u)=\phi(v\div a)$
- $\phi(ua)=\phi(vb) \wedge a \neq b \implies (a,b)\in I$
-/
@[ext]
structure DependenceMorphism (M : Type*) [Monoid M] where
  /-- The underlying homomophism from the free monoid of strings to another monoid `M`. -/
  toFun : List α →* M
  A1 : ∀ w, toFun w = toFun 1 → w = []
  A2 : ∀ {a b}, I.rel a b → toFun [a, b] = toFun [b, a]
  A3 : ∀ {u v} {a}, toFun (u ++ [a]) = toFun v → toFun u = toFun (v ÷ a)
  A4 : ∀ {u v} {a b}, toFun (u ++ [a]) = toFun (v ++ [b]) ∧ a ≠ b → I.rel a b

instance {M} [Monoid M] :
    CoeFun (DependenceMorphism I M) (fun _ ↦ FreeMonoid α → M) where
  coe := fun morphism ↦ morphism.toFun

attribute [coe] DependenceMorphism.toFun

theorem DependenceMorphism.map_append {I M} [Monoid M]
    (ϕ : DependenceMorphism I M) (u v : List α) :
    ϕ (u ++ v) = ϕ u * ϕ v :=
  ϕ.toFun.map_mul u v

/-- The natural homomorphism from the free monoid `List α` to the trace monoid `Trace I`. -/
def mk' : List α →* Trace I where
  toFun := Quotient.mk (traceSetoid I)
  map_one' := rfl
  map_mul' := by
    intro w₁ w₂
    rfl

/-- The natural homomorphism from the free monoid of strings to the trace monoid
is a dependence morphism. -/
def traceDependenceMorphism : DependenceMorphism I (Trace I) where
  toFun := mk'
  A1 := by
    intro w hw
    replace hw := Quotient.exact hw
    apply List.length_eq_zero_iff.mp
    exact length_eq_of_equiv hw
  A2 := by
    intro a b hab
    apply Quotient.sound
    exact TraceEquiv.swap a b hab
  A3 := by
    intro u v a huav
    replace huav := Quotient.exact huav
    apply Quotient.sound
    have h_cancel : TraceEquiv I (u ++ [a] ÷ a) (v ÷ a) := cancelRight_congr a huav
    simp at h_cancel
    exact h_cancel
  A4 := by
    intro u v a b huvab
    have h_equiv := Quotient.exact huvab.left
    have h_indep := indep_and_exists_of_equiv_of_tail_ne h_equiv huvab.right
    exact h_indep.left

variable {M N : Type*} [Monoid M] [Monoid N]

lemma exists_of_image_eq_of_tail_ne {ϕ : DependenceMorphism I M} {u v : List α} {a b : α}
    (heq : ϕ (u ++ [a]) = ϕ (v ++ [b])) (hne : a ≠ b) :
    ∃ w, ϕ u = ϕ (w ++ [b]) ∧ ϕ v = ϕ (w ++ [a]) := by
  have hu : ϕ u = ϕ (v ÷ a ++ [b]) := by simpa [append_cancelRight, hne] using ϕ.A3 heq
  have hu' : ϕ (u ÷ b) = ϕ (v ÷ a) := (ϕ.A3 hu.symm).symm
  use u ÷ b
  constructor
  · rw [hu, ϕ.map_append, ϕ.map_append, hu']
  · have hab : u ÷ b ++ [a] = u ++ [a] ÷ b := by simp [hne, Ne.symm]
    rw [hab]
    exact ϕ.A3 heq.symm

theorem image_eq_of_image_eq
    (ϕ : DependenceMorphism I M) (ψ : DependenceMorphism I N)
    (x y : List α) (h : ϕ x = ϕ y) :
    ψ x = ψ y := by
  induction x using List.reverseRecOn generalizing y with
  | nil =>
    replace h := ϕ.A1 y h.symm
    rw [h]
  | append_singleton u a ihx =>
    induction y using List.reverseRecOn generalizing u a with
    | nil =>
      replace h := ϕ.A1 (u ++ [a]) h
      rw [h]
    | append_singleton v b ihy =>
      by_cases hab : a = b
      · replace h := ϕ.A3 h
        simp [hab] at h
        rw [ψ.map_append, ψ.map_append]
        rw [ihx v, hab]
        exact h
      · have h_indep := ϕ.A4 ⟨h, hab⟩
        have ⟨w, hw⟩ := exists_of_image_eq_of_tail_ne h hab
        have hwb := ihx (w ++ [b]) hw.left
        have h' : ∀ z, ϕ w = ϕ z → ψ w = ψ z := by
          intro z hz
          have hu := hw.left
          rw [ϕ.map_append, hz, ← ϕ.map_append] at hu
          replace hu := ihx (z ++ [b]) hu
          have hwz := ψ.A3 (hwb.symm.trans hu)
          simp at hwz
          exact hwz
        have hwa := (ihy w a h' hw.right.symm).symm
        rw [ψ.map_append, ψ.map_append, hwb, hwa, ← ψ.map_append, ← ψ.map_append]
        rw [List.append_assoc, List.append_assoc]
        rw [ψ.map_append, ψ.map_append w]
        rw [List.singleton_append, List.singleton_append]
        rw [ψ.A2 h_indep]

/-- Two monoids `M` and `N` are isomorphic given surjective dependence morphisms w.r.t. the
same dependency into them. -/
noncomputable def dependenceMorphismIso
    (ϕ : DependenceMorphism I M) (hϕ_surj : Function.Surjective ϕ.toFun)
    (ψ : DependenceMorphism I N) (hψ_surj : Function.Surjective ψ.toFun) :
    M ≃* N := by
  let θ (m : M) : N := ψ (Classical.choose (hϕ_surj m))
  let θ_inv (n : N) : M := ϕ (Classical.choose (hψ_surj n))
  have θ_well_defined : ∀ (m : M) (w : List α) (h : ϕ w = m), θ m = ψ w := by
    intro m w h
    have h_choose := Classical.choose_spec (hϕ_surj m)
    rw [← h_choose, ] at h
    exact image_eq_of_image_eq ϕ ψ _ _ h.symm
  have θ_inv_well_defined : ∀ (n : N) (w : List α) (h : ψ w = n), θ_inv n = ϕ w := by
    intro n w h
    have h_choose := Classical.choose_spec (hψ_surj n)
    rw [← h_choose] at h
    exact image_eq_of_image_eq ψ ϕ _ _ h.symm
  refine' {
    toFun := θ
    invFun := θ_inv
    map_mul' := ?_
    left_inv := ?_
    right_inv := ?_
  }
  · intro m
    rcases hϕ_surj m with ⟨w, hw⟩
    rw [θ_well_defined m w hw]
    rw [θ_inv_well_defined (ψ w) w rfl]
    exact hw
  · intro n
    rcases hψ_surj n with ⟨w, hw⟩
    rw [θ_inv_well_defined n w hw]
    rw [θ_well_defined (ϕ w) w rfl]
    exact hw
  · intro m₁ m₂
    rcases hϕ_surj m₁ with ⟨w₁, hw₁⟩
    rcases hϕ_surj m₂ with ⟨w₂, hw₂⟩
    rw [θ_well_defined m₁ w₁ hw₁]
    rw [θ_well_defined m₂ w₂ hw₂]
    rw [← ψ.map_append]
    have h : ϕ (w₁ ++ w₂) = m₁ * m₂ := by
      rw [ϕ.map_append, hw₁, hw₂]
    exact θ_well_defined (m₁ * m₂) (w₁ ++ w₂) h

end TraceTheory
