import Mathlib.Algebra.FreeMonoid.Basic

namespace TraceTheory

variable {α : Type*}

/-- A dependence is a finite, reflexive, and symmetric relation. -/
structure Dependence (α : Type*) where
  /-- The dependence relation. -/
  rel : α → α → Prop
  refl : ∀ a, rel a a
  symm: ∀ a b, rel a b → rel b a

/-- An independence is a finite, irreflexive, and symmetric relation. -/
structure Independence (α : Type*) where
  /-- The independence relation. -/
  rel : α → α → Prop
  irrefl : ∀ a, ¬ rel a a
  symm : ∀ a b, rel a b → rel b a

/-- The Dependence relation induced by an Independence `I`. -/
def inducedDependence {α : Type*} (I : Independence α) : Dependence α where
  rel := fun a b => ¬ I.rel a b
  refl := by
    intro a
    exact I.irrefl a
  symm := by
    intro a b hab hba
    exact hab (I.symm b a hba)

/-- The Independence relation induced by a Dependence `D`. -/
def inducedIndependence {α : Type*} (D : Dependence α) : Independence α where
  rel := fun a b => ¬D.rel a b
  irrefl := by
    intro a h
    exact h (D.refl a)
  symm := by
    intro a b hab hba
    exact hab (D.symm b a hba)

/-- Strings $u,v$ are independent if every symbol in $u$ is independent of every symbol in $v$. -/
@[simp]
def Independent (I : Independence α) (u v : List α) := ∀ a ∈ u, ∀ b ∈ v, I.rel a b

/-- The binary relation $~$ such that $u~v$ if and only if there exists strings $x,y$ and symbols
  $a,b$ such that $aIb$, $u=xaby$ and $v=xbay$. -/
inductive SwapOnce (I : Independence α) : List α → List α → Prop
  | swap (a b : α) : I.rel a b → SwapOnce I [a, b] [b, a]

/-- The trace equivalence relation is the least congruence $\equiv$ such that for all symbols
  $a$ and $b$, $(a,b) \in I \leftrightarrow ab \equiv ba$.

  Intuitively, two strings (lists of symbols) are equivalent if one can be transformed into the other
  by a finite sequence of swaps of adjacent independent symbols.

  The relation is inductively generated by:
- **Swap:** If `I.rel a b`, then `[a, b]` is equivalent to `[b, a]` (swapping adjacent independent
  symbols).
- **Reflexivity:** Every word is equivalent to itself.
- **Symmetry:** If `w₁` is equivalent to `w₂`, then `w₂` is equivalent to `w₁`.
- **Transitivity:** If `w₁` is equivalent to `w₂` and `w₂` is equivalent to `w₃`, then `w₁` is
  equivalent to `w₃`.
- **Compatibility:** If `w₁` is equivalent to `w₂` and `w₃` is equivalent to `w₄`, then `w₁ ++ w₃`
  is equivalent to `w₂ ++ w₄`. -/
inductive TraceEqv (I : Independence α) : List α → List α → Prop
  | swap : ∀ a b, I.rel a b → TraceEqv I [a, b] [b, a]
  | refl : ∀ w₁, TraceEqv I w₁ w₁
  | symm : ∀ {w₁ w₂}, TraceEqv I w₁ w₂ → TraceEqv I w₂ w₁
  | trans : ∀ {w₁ w₂ w₃},
      TraceEqv I w₁ w₂ →
      TraceEqv I w₂ w₃ →
      TraceEqv I w₁ w₃
  | compat : ∀ {w₁ w₂ w₃ w₄},
      TraceEqv I w₁ w₂ →
      TraceEqv I w₃ w₄ →
      TraceEqv I (w₁ ++ w₃) (w₂ ++ w₄)

instance : CancelMonoid (List α) where
  one := List.nil
  mul := List.append
  mul_assoc := List.append_assoc
  mul_one := List.append_nil
  one_mul := List.nil_append
  mul_left_cancel := by
    intro a b c heq
    exact List.append_cancel_left heq
  mul_right_cancel := by
    intro a b c heq
    exact List.append_cancel_right heq

/-- The setoid structure on strings defined by the trace equivalence relation `TraceEqv I`.
  This serves as the basis for constructing the quotient type `TraceMonoid`. -/
def TraceSetoid (I : Independence α) : Setoid (List α) where
  r := TraceEqv I
  iseqv := Equivalence.mk TraceEqv.refl TraceEqv.symm TraceEqv.trans

/-- The type of Mazurkiewicz traces, defined as the quotient of the free monoid
  by the trace equivalence relation induced by `I`. -/
def Trace (I : Independence α) := Quotient (TraceSetoid I)

namespace Trace

variable {I : Independence α} [DecidableEq α]

/-- Composition (concatenation) of traces. This is induced by the concatenation
  operation on the underlying strings. -/
@[simp]
def mul : Trace I -> Trace I -> Trace I :=
  Quotient.lift₂
    (fun w₁ w₂ => ⟦w₁ ++ w₂⟧)
    (by
      intro a₁ b₁ a₂ b₂ ha hb
      apply Quotient.sound
      exact ha.compat hb
    )

/-- The empty trace, represented by the equivalence class of the empty list. -/
def one := Quotient.mk (TraceSetoid I) []

instance : Monoid (Trace I) where
  mul := mul
  one := one
  mul_assoc := by
    intro t₁ t₂ t₃
    refine Quotient.inductionOn₃ t₁ t₂ t₃ (fun w₁ w₂ w₃ => ?_)
    apply Quotient.sound
    rw [List.append_assoc]
    exact TraceEqv.refl _
  one_mul := by
    intro t
    refine Quotient.inductionOn t (fun w => ?_)
    apply Quotient.sound
    rw [List.nil_append]
    exact TraceEqv.refl _
  mul_one := by
    intro t
    refine Quotient.inductionOn t (fun w => ?_)
    apply Quotient.sound
    rw [List.append_nil]
    exact TraceEqv.refl _

/-- The natural homomorphism from the free monoid `List α` to the trace monoid `Trace I`. -/
def mk' (I : Independence α) : List α →* Trace I where
  toFun := Quotient.mk (TraceSetoid I)
  map_one' := rfl
  map_mul' := by
    intro x y
    rfl

omit [DecidableEq α] in
@[simp]
theorem mk'_nil : mk' (I := I) [] = 1 := map_one _

/-- The prefix relation on traces. A trace `t₁` is a prefix of `t₂` if there exists
  a trace `⟦w⟧` such that `t₁` concatenated with `⟦w⟧` equals `t₂`. -/
def IsPrefix (I : Independence α) (t₁ t₂ : Trace I) := ∃ w, mul t₁ ⟦w⟧ = t₂

end Trace

end TraceTheory
