import Mathlib.Algebra.Group.Submonoid.Basic
import TraceTheory.Trace

open Trace

namespace History

variable {α : Type} [DecidableEq α] {n : ℕ}

/-- The product monoid P(Σ) of n-tuples. -/
def ProductMonoid (Sigma : Fin n → Finset α) := ∀ i : Fin n, List (Sigma i)

variable {Sigma : Fin n → Finset α}

instance : Monoid (ProductMonoid Sigma) := Pi.monoid

/-- Auxiliary function for defining projection. -/
def projChar (i : Fin n) (a : α) : Option (Sigma i) :=
  if h : a ∈ Sigma i then Option.some ⟨a, h⟩ else Option.none

/-- The projection function from a string onto an alphabet of a n-tuple. -/
def proj (i : Fin n) : List α →* List (Sigma i) where
  toFun w := w.filterMap (projChar i)
  map_one' := by rfl
  map_mul' := by
    intro x y
    exact List.filterMap_append

/-- The distribution function π(w) which returns the projections of w onto each alphabet. -/
def distribution : List α →* ProductMonoid Sigma where
  toFun w := fun i => proj i w
  map_one' := by rfl
  map_mul' := by
    intro x y
    funext i
    exact (proj i).map_mul' x y

/-- Elementary history of symbol `a`. -/
def elementaryHistory (a : α) : ProductMonoid Sigma := distribution [a]

/-- The set of all elementary histories. -/
def elementaryHistorySet : Set (ProductMonoid Sigma) :=
  { h | ∃ a, h = elementaryHistory a}

/-- The submonoid H(Σ) generated by elementary histories. -/
def HistoryMonoid : Submonoid (ProductMonoid Sigma) :=
  Submonoid.closure elementaryHistorySet
