import Mathlib.Algebra.Group.Submonoid.Basic
import TraceTheory.Trace

open Trace

namespace History

variable {α : Type} [DecidableEq α] {n : ℕ}

/-- The product monoid P(Σ) of n-tuples. -/
def ProductMonoid (Sigma : Fin n → Finset α) := ∀ i : Fin n, List (Sigma i)

instance (Sigma : Fin n → Finset α) : Monoid (ProductMonoid Sigma) := Pi.monoid

/-- Auxiliary function for defining projection. -/
def projChar (Sigma : Fin n → Finset α) (i : Fin n) (a : α) : Option (Sigma i) :=
  if h : a ∈ Sigma i then Option.some ⟨a, h⟩ else Option.none

/-- The projection function from a string onto an alphabet of a n-tuple. -/
def proj (Sigma : Fin n → Finset α) (i : Fin n) : List α →* List (Sigma i) where
  toFun w := w.filterMap (projChar Sigma i)
  map_one' := by rfl
  map_mul' := by
    intro x y
    exact List.filterMap_append

/-- The distribution function π(w) which returns the projections of w onto each alphabet. -/
def distribution (Sigma : Fin n → Finset α) : List α →* ProductMonoid Sigma where
  toFun w := fun i => proj Sigma i w
  map_one' := by rfl
  map_mul' := by
    intro x y
    funext i
    exact (proj Sigma i).map_mul' x y

/-- Elementary history of symbol `a`. -/
def elementaryHistory (Sigma : Fin n → Finset α) (a : α) : ProductMonoid Sigma :=
  distribution Sigma [a]

/-- The set of all elementary histories. -/
def elementaryHistorySet (Sigma : Fin n → Finset α) : Set (ProductMonoid Sigma) :=
  { h | ∃ a, h = elementaryHistory Sigma a}

/-- The submonoid H(Σ) generated by elementary histories. -/
def HistoryMonoid (Sigma : Fin n → Finset α) : Submonoid (ProductMonoid Sigma) :=
  Submonoid.closure (elementaryHistorySet Sigma)

lemma distribution.map_append (Sigma : Fin n → Finset α) (w₁ w₂ : List α) :
    distribution Sigma (w₁ ++ w₂) = distribution Sigma w₁ * distribution Sigma w₂ :=
  (distribution Sigma).map_mul w₁ w₂

lemma distribution_mem_historyMonoid (Sigma : Fin n → Finset α) (w : List α) :
    distribution Sigma w ∈ HistoryMonoid Sigma := by
  induction w with
  | nil =>
    exact (HistoryMonoid Sigma).one_mem
  | cons a w' ih =>
    rw [(show a :: w' = [a] ++ w' from rfl), distribution.map_append]
    apply (HistoryMonoid Sigma).mul_mem
    · apply Submonoid.subset_closure
      use a
      rfl
    · exact ih

-- Proposition (1.5.2)
/-- The distribution function with codomain restricted to the monoid of histories. -/
def distribution' (Sigma : Fin n → Finset α) : List α →* HistoryMonoid Sigma where
  toFun w := ⟨distribution Sigma w, distribution_mem_historyMonoid Sigma w⟩
  map_one' := Subtype.eq (distribution Sigma).map_one
  map_mul' x y := Subtype.eq ((distribution Sigma).map_mul x y)

lemma distribution'.map_append (Sigma : Fin n → Finset α) (w₁ w₂ : List α) :
    distribution' Sigma (w₁ ++ w₂) = distribution' Sigma w₁ * distribution' Sigma w₂ :=
  (distribution' Sigma).map_mul w₁ w₂

lemma distribution'_surjective (Sigma : Fin n → Finset α) :
    Function.Surjective (distribution' Sigma) := by
  intro ⟨y, hy⟩
  induction hy using Submonoid.closure_induction with
  | mem x hx =>
    have ⟨a, ha⟩ := hx
    use [a]
    exact SetLike.coe_eq_coe.mp (Eq.symm ha)
  | one =>
    use []
    rfl
  | mul x y hx hy ihx ihy =>
    rcases ihx with ⟨u, hu⟩
    rcases ihy with ⟨v, hv⟩
    use u ++ v
    rw [distribution'.map_append]
    apply SetLike.coe_eq_coe.mp
    rw [hu, hv]
    rfl

/-- The dependence relation defined by a tuple of alphabets. -/
def SigmaDependence (Sigma : Fin n → Finset α) (h_cover : ∀ a, ∃ i, a ∈ Sigma i) :
    Dependence α where
  rel a b := ∃ i, a ∈ Sigma i ∧ b ∈ Sigma i
  refl := by
    intro a
    have ⟨i, hi⟩ := h_cover a
    use i, hi, hi
  symm := by
    intro a b ⟨i, ha, hb⟩
    use i, hb, ha

lemma proj_cancel_right (Sigma : Fin n → Finset α) (i : Fin n) (w : List α) (a : α) :
    proj Sigma i (w ÷ a) =
      if h : a ∈ Sigma i then (proj Sigma i w) ÷ ⟨a, h⟩ else proj Sigma i w := by
  simp [proj]
  split_ifs with h
  · induction w using List.induction_right with
    | nil =>
      rfl
    | snoc w' b ih =>
      by_cases hb : a = b
      · subst hb
        simp [projChar, h]
      · simp [hb]
        rw [ih]
        simp only [right_eq_ite_iff]
        intro h_proj
        simp [projChar] at h_proj
        exfalso
        exact hb (Eq.symm h_proj.right)
  · induction w using List.induction_right with
    | nil =>
      rfl
    | snoc w' b ih =>
      by_cases hb : a = b
      · subst hb
        simp [projChar, h]
      · simp [hb]
        exact ih

-- Theorem 1.5.3
/-- Distribution is a dependence morphism. -/
def historyDependenceMorphism (Sigma : Fin n → Finset α) (h_cover : ∀ a, ∃ i, a ∈ Sigma i) :
    DependenceMorphism
      (inducedIndependence (SigmaDependence Sigma h_cover))
      (HistoryMonoid Sigma) where
  toFun := distribution' Sigma
  A1 := by
    intro w heq
    have hw : distribution Sigma w = 1 := by
      apply Subtype.ext_iff.mp heq
    cases w with
    | nil =>
      rfl
    | cons a w' =>
      have ⟨i, hi⟩ := h_cover a
      have h_proj : proj Sigma i (a :: w') = [] := by
        have h_fun := congr_fun hw i
        dsimp [distribution] at h_fun
        exact h_fun
      dsimp only [proj, MonoidHom.coe_mk, OneHom.coe_mk] at h_proj
      simp [projChar, hi] at h_proj
  A2 := by
    intro a b h_indep
    simp [distribution', distribution, proj]
    funext i
    rw [(show [a, b] = [a] ++ [b] from rfl), (show [b, a] = [b] ++ [a] from rfl)]
    by_cases ha : a ∈ Sigma i <;> by_cases hb : b ∈ Sigma i
    · exfalso
      dsimp [inducedIndependence, SigmaDependence] at h_indep
      exact h_indep ⟨i, ha, hb⟩
    · simp [projChar, ha, hb]
    · simp [projChar, ha, hb]
    · simp [projChar, ha, hb]
  A3 := by
    intro w₁ w₂ a heq
    simp [distribution', distribution]
    funext i
    have hi : proj Sigma i (w₁ ++ [a]) = proj Sigma i w₂ := by
      rw [Subtype.ext_iff] at heq
      exact congr_fun heq i
    rw [proj_cancel_right]
    by_cases h : a ∈ Sigma i
    · have hi' : proj Sigma i (w₁ ++ [a]) ÷ ⟨a, h⟩ = proj Sigma i w₂ ÷ ⟨a, h⟩ := by rw [hi]
      simp [proj, projChar, h] at hi' ⊢
      exact hi'
    · simp [proj, projChar, h] at hi ⊢
      exact hi
  A4 := by
    intro w₁ w₂ a b ⟨heq, hne⟩ ⟨i, ha, hb⟩
    have hi : proj Sigma i (w₁ ++ [a]) = proj Sigma i (w₂ ++ [b]) := by
      rw [Subtype.ext_iff] at heq
      exact congr_fun heq i
    simp [proj, projChar, ha, hb] at hi
    have h_last {β} {w₁ w₂ : List β} {a b : β} (h : w₁ ++ [a] = w₂ ++ [b]) : a = b := by
      have hrev : (w₁ ++ [a]).reverse = (w₂ ++ [b]).reverse := congrArg List.reverse h
      simp at hrev
      exact hrev.left
    have h_last_eq := Subtype.mk_eq_mk.mp (h_last hi)
    contradiction

-- Theorem 1.5.4
/-- The trace monoid and `HistoryMonoid` are isomorphic. -/
noncomputable def traceMonoidIsoHistoryMonoid
    (Sigma : Fin n → Finset α) (h_cover : ∀ a, ∃ i, a ∈ Sigma i) :
    Trace (inducedIndependence (SigmaDependence Sigma h_cover)) ≃* HistoryMonoid (Sigma) := by
  apply dependenceMorphismIso
    traceDependenceMorphism
    Quotient.mk_surjective
    (historyDependenceMorphism Sigma h_cover)
    (distribution'_surjective Sigma)
