import Mathlib.Algebra.Group.Submonoid.Basic
import Mathlib.Algebra.Group.Pi.Basic
import TraceTheory.DependenceMorphism

open List

namespace TraceTheory

namespace History

variable {α : Type} [DecidableEq α] {n : ℕ}

/-- The product monoid P(Σ) of n-tuples. -/
def ProductMonoid (S : Fin n → Finset α) := ∀ i : Fin n, List (S i)

instance (S : Fin n → Finset α) : Monoid (ProductMonoid S) := Pi.monoid

/-- Auxiliary function for defining projection. -/
def projChar (S : Fin n → Finset α) (i : Fin n) (a : α) : Option (S i) :=
  if h : a ∈ S i then Option.some ⟨a, h⟩ else Option.none

/-- The projection function from a string onto an alphabet of a n-tuple. -/
def proj (S : Fin n → Finset α) (i : Fin n) : List α →* List (S i) where
  toFun w := w.filterMap (projChar S i)
  map_one' := by rfl
  map_mul' := by
    intro x y
    exact List.filterMap_append

/-- The distribution function π(w) which returns the projections of w onto each alphabet. -/
def distribution (S : Fin n → Finset α) : List α →* ProductMonoid S where
  toFun w := fun i => proj S i w
  map_one' := by rfl
  map_mul' := by
    intro x y
    funext i
    exact (proj S i).map_mul' x y

/-- Elementary history of symbol `a`. -/
def elementaryHistory (S : Fin n → Finset α) (a : α) : ProductMonoid S :=
  distribution S [a]

/-- The set of all elementary histories. -/
def elementaryHistorySet (S : Fin n → Finset α) : Set (ProductMonoid S) :=
  { h | ∃ a, h = elementaryHistory S a}

/-- The submonoid H(Σ) generated by elementary histories. -/
def _root_.History (S : Fin n → Finset α) : Submonoid (ProductMonoid S) :=
  Submonoid.closure (elementaryHistorySet S)

theorem distribution.map_append (S : Fin n → Finset α) (w₁ w₂ : List α) :
    distribution S (w₁ ++ w₂) = distribution S w₁ * distribution S w₂ :=
  (distribution S).map_mul w₁ w₂

theorem distribution_mem_historyMonoid (S : Fin n → Finset α) (w : List α) :
    distribution S w ∈ History S := by
  induction w with
  | nil =>
    exact (History S).one_mem
  | cons a w' ih =>
    rw [(show a :: w' = [a] ++ w' from rfl), distribution.map_append]
    apply (History S).mul_mem
    · apply Submonoid.subset_closure
      use a
      rfl
    · exact ih

/-- The distribution function with codomain restricted to the monoid of histories. -/
def distribution' (S : Fin n → Finset α) : List α →* History S where
  toFun w := ⟨distribution S w, distribution_mem_historyMonoid S w⟩
  map_one' := Subtype.ext (distribution S).map_one
  map_mul' x y := Subtype.ext ((distribution S).map_mul x y)

theorem distribution'.map_append (S : Fin n → Finset α) (w₁ w₂ : List α) :
    distribution' S (w₁ ++ w₂) = distribution' S w₁ * distribution' S w₂ :=
  (distribution' S).map_mul w₁ w₂

theorem distribution'_surjective (S : Fin n → Finset α) :
    Function.Surjective (distribution' S) := by
  intro ⟨y, hy⟩
  induction hy using Submonoid.closure_induction with
  | mem x hx =>
    have ⟨a, ha⟩ := hx
    use [a]
    exact SetLike.coe_eq_coe.mp (Eq.symm ha)
  | one =>
    use []
    rfl
  | mul x y hx hy ihx ihy =>
    rcases ihx with ⟨u, hu⟩
    rcases ihy with ⟨v, hv⟩
    use u ++ v
    rw [distribution'.map_append]
    apply SetLike.coe_eq_coe.mp
    rw [hu, hv]
    rfl

/-- The dependence relation defined by a tuple of alphabets. -/
def SigmaDependence (S : Fin n → Finset α) (h_cover : ∀ a, ∃ i, a ∈ S i) :
    Dependence α where
  rel a b := ∃ i, a ∈ S i ∧ b ∈ S i
  refl := by
    intro a
    have ⟨i, hi⟩ := h_cover a
    use i, hi, hi
  symm := by
    intro a b ⟨i, ha, hb⟩
    use i, hb, ha

theorem proj_append (S : Fin n → Finset α) (i : Fin n) (w₁ w₂ : List α) :
    proj S i (w₁ ++ w₂) = (proj S i w₁) ++ (proj S i w₂) := by
  simp [proj]

theorem proj_cancelRight (S : Fin n → Finset α) (i : Fin n) (w : List α) (a : α) :
    proj S i (w ÷ a) =
      if h : a ∈ S i then (proj S i w) ÷ ⟨a, h⟩ else proj S i w := by
  induction w using List.reverseRecOn with
  | nil =>
    split_ifs <;> rfl
  | append_singleton w' b ih =>
    split_ifs with h_mem <;> by_cases heq : a = b
    · subst heq
      simp [proj, projChar, h_mem]
    · simp [h_mem] at ih
      simp [heq]
      simp only [proj_append, ih, append_cancelRight]
      split_ifs with h_mem'
      · exfalso
        simp [proj, projChar] at h_mem'
        exact heq h_mem'.right.symm
      · rfl
    · subst heq
      simp [proj, projChar, h_mem]
    · simp [h_mem] at ih
      simp [heq]
      simp only [proj_append, ih]

/-- Distribution is a dependence morphism. -/
def historyDependenceMorphism (S : Fin n → Finset α) (h_cover : ∀ a, ∃ i, a ∈ S i) :
    DependenceMorphism
      (inducedIndependence (SigmaDependence S h_cover))
      (History S) where
  toFun := distribution' S
  A1 := by
    intro w heq
    have hw : distribution S w = 1 := by
      apply Subtype.ext_iff.mp heq
    cases w with
    | nil =>
      rfl
    | cons a w' =>
      have ⟨i, hi⟩ := h_cover a
      have h_proj : proj S i (a :: w') = [] := by
        have h_fun := congr_fun hw i
        dsimp [distribution] at h_fun
        exact h_fun
      dsimp only [proj, MonoidHom.coe_mk, OneHom.coe_mk] at h_proj
      simp [projChar, hi] at h_proj
  A2 := by
    intro a b h_indep
    simp [distribution', distribution, proj]
    funext i
    rw [(show [a, b] = [a] ++ [b] from rfl), (show [b, a] = [b] ++ [a] from rfl)]
    by_cases ha : a ∈ S i <;> by_cases hb : b ∈ S i
    · exfalso
      dsimp [inducedIndependence, SigmaDependence] at h_indep
      exact h_indep ⟨i, ha, hb⟩
    · simp [projChar, ha, hb]
    · simp [projChar, ha, hb]
    · simp [projChar, ha, hb]
  A3 := by
    intro w₁ w₂ a heq
    simp [distribution', distribution]
    funext i
    have hi : proj S i (w₁ ++ [a]) = proj S i w₂ := by
      rw [Subtype.ext_iff] at heq
      exact congr_fun heq i
    rw [proj_cancelRight]
    by_cases h : a ∈ S i
    · have hi' : proj S i (w₁ ++ [a]) ÷ ⟨a, h⟩ = proj S i w₂ ÷ ⟨a, h⟩ := by rw [hi]
      simpa [proj, projChar, h] using hi'
    · simpa [proj, projChar, h] using hi
  A4 := by
    intro w₁ w₂ a b ⟨heq, hne⟩ ⟨i, ha, hb⟩
    have hi : proj S i (w₁ ++ [a]) = proj S i (w₂ ++ [b]) := by
      rw [Subtype.ext_iff] at heq
      exact congr_fun heq i
    simp [proj, projChar, ha, hb] at hi
    have ⟨_, h_absurd⟩ := hi
    contradiction

/-- The trace monoid and `HistoryMonoid` are isomorphic. -/
noncomputable def traceMonoidIsoHistoryMonoid
    (S : Fin n → Finset α) (h_cover : ∀ a, ∃ i, a ∈ S i) :
    Trace (inducedIndependence (SigmaDependence S h_cover)) ≃* History S := by
  apply dependenceMorphismIso
    traceDependenceMorphism
    Quotient.mk_surjective
    (historyDependenceMorphism S h_cover)
    (distribution'_surjective S)

end History

end TraceTheory
