import Mathlib.Data.Fintype.Basic
import TraceTheory.Basic

variable {α : Type*} [DecidableEq α]

namespace Trace

/-- A dependency is a finite, reflexive, and symmetric relation. -/
structure Dependency (α : Type*) where
  rel : α → α → Prop
  refl : ∀ a, rel a a
  symm: ∀ a b, rel a b → rel b a

/-- An independency is a finite, irreflexive, and symmetric relation. -/
structure Independency (α : Type*) where
  rel : α → α → Prop
  irrefl : ∀ a, ¬ rel a a
  symm : ∀ a b, rel a b → rel b a

/-- The Independency relation induced by a Dependency `D`. -/
def inducedIndependency {α : Type*} (D : Dependency α) : Independency α :=
  { rel    := fun a b => ¬ D.rel a b,
    irrefl := by
      intro a h
      exact h (D.refl a),
    symm   := by
      intro a b h
      exact h ∘ (D.symm b a) }

variable {I : Independency α}

variable (I) in
/--
The trace equivalence relation is the least congruence $\equiv$ such that for all symbols
$a$ and $b$, $(a,b) \in I \leftrightarrow ab \equiv ba$.

Intuitively, two strings (lists of symbols) are equivalent if one can be transformed into the other
by a finite sequence of swaps of adjacent independent symbols.

The relation is inductively generated by:
- **Swap:** If `I.rel a b`, then `[a, b]` is equivalent to `[b, a]` (swapping adjacent independent
  symbols).
- **Reflexivity:** Every word is equivalent to itself.
- **Symmetry:** If `w₁` is equivalent to `w₂`, then `w₂` is equivalent to `w₁`.
- **Transitivity:** If `w₁` is equivalent to `w₂` and `w₂` is equivalent to `w₃`, then `w₁` is
  equivalent to `w₃`.
- **Compatibility:** If `w₁` is equivalent to `w₂` and `w₃` is equivalent to `w₄`, then `w₁ ++ w₃`
  is equivalent to `w₂ ++ w₄`.
-/
inductive TraceEquiv : List α → List α → Prop
  | swap : ∀ a b, I.rel a b → TraceEquiv [a, b] [b, a]
  | refl : ∀ w₁, TraceEquiv w₁ w₁
  | symm : ∀ {w₁ w₂}, TraceEquiv w₁ w₂ → TraceEquiv w₂ w₁
  | trans : ∀ {w₁ w₂ w₃}, TraceEquiv w₁ w₂ → TraceEquiv w₂ w₃ → TraceEquiv w₁ w₃
  | compat : ∀ {w₁ w₂ w₃ w₄}, TraceEquiv w₁ w₂ → TraceEquiv w₃ w₄ → TraceEquiv (w₁ ++ w₃) (w₂ ++ w₄)

omit [DecidableEq α] in
variable (I) in
lemma equiv_implies_length_eq {w₁ w₂ : List α} (h : TraceEquiv I w₁ w₂):
    w₁.length = w₂.length := by
  induction h with
  | swap _ _ _ =>
    rfl
  | refl _ =>
    rfl
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp [ih₁, ih₂]

omit [DecidableEq α] in
variable (I) in
lemma equiv_implies_alph_eq {w₁ w₂ : List α} (a : α) (h : TraceEquiv I w₁ w₂) :
    (a ∈ w₁ ↔ a ∈ w₂) := by
  induction h with
  | swap _ _ _ =>
    simp
    exact Or.comm
  | refl _ =>
    exact Eq.to_iff rfl
  | symm _ ih =>
    exact Iff.symm ih
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact or_congr ih₁ ih₂

omit [DecidableEq α] in
variable (I) in
lemma mirror_rule {w₁ w₂ : List α} (h : TraceEquiv I w₁ w₂) : -- (1.6)
    TraceEquiv I w₁.reverse w₂.reverse := by
  induction h with
  | swap a b h =>
    simp
    exact TraceEquiv.swap b a (I.symm a b h)
  | refl w₁' =>
    exact TraceEquiv.refl w₁'.reverse
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact ih₂.compat ih₁

infixl:65 " ÷ " => List.cancel_right

@[simp]
lemma cancel_right_over_concat {w₁ w₂ : List α} (a : α) :
    (w₁ ++ w₂) ÷ a = if (a ∈ w₂) then w₁ ++ (w₂ ÷ a) else (w₁ ÷ a) ++ w₂ := by
  induction w₂ using List.induction_right with
  | nil =>
    simp
  | snoc w₂' a' ih =>
    nth_rw 1 [← List.append_assoc]
    by_cases ha : a ∈ w₂'
    all_goals
      by_cases heq : a = a'
      · rw [List.cancel_right_snoc]
        simp [heq]
      · rw [List.cancel_right_snoc]
        simp [ha, heq, ih]

variable (I) in
lemma cancellation_rule {w₁ w₂ : List α} (a : α) (h : TraceEquiv I w₁ w₂) : -- (1.7)
    TraceEquiv I (w₁ ÷ a) (w₂ ÷ a) := by
  induction h with
  | swap b c hbc =>
    by_cases hab : a = b <;> by_cases hac : a = c
    · rw [← hab, ← hac]
      exact TraceEquiv.refl _
    · rw [← hab]
      simp [List.cancel_right, hac]
      exact TraceEquiv.refl _
    · rw [← hac]
      simp [List.cancel_right, hab]
      exact TraceEquiv.refl _
    · simp [List.cancel_right, hab, hac]
      exact TraceEquiv.swap b c hbc
  | refl _ =>
    exact TraceEquiv.refl _
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat t₁ t₂ ih₁ ih₂ =>
    rename_i l₃ _
    by_cases hal₃ : a ∈ l₃
    · have hal₄ := (equiv_implies_alph_eq I a t₂).mp hal₃
      simp [hal₃, hal₄]
      exact t₁.compat ih₂
    · have hal₄ := (equiv_implies_alph_eq I a t₂).mpr.mt hal₃
      simp [hal₃, hal₄]
      exact ih₁.compat t₂

variable (I) in
lemma cancellation_rule_left {w₁ w₂ : List α} (a : α) (h : TraceEquiv I w₁ w₂) :
    TraceEquiv I (w₁.cancel_left a) (w₂.cancel_left a) := by
  rw [List.cancel_left_eq_rev_cancel_right_rev, List.cancel_left_eq_rev_cancel_right_rev]
  exact mirror_rule I (cancellation_rule I a (mirror_rule I h))

variable (I) in
lemma projection_rule {w₁ w₂ : List α} (Sigma : Alphabet α) (h : TraceEquiv I w₁ w₂) : -- (1.8)
    TraceEquiv I (w₁.proj Sigma) (w₂.proj Sigma) := by
  induction h with
  | swap a b h =>
    by_cases ha : a ∈ Sigma <;> by_cases hb : b ∈ Sigma
    all_goals (
      simp [List.proj, ha, hb]
      try exact TraceEquiv.swap a b h
      try exact TraceEquiv.refl _
    )
  | refl _ =>
    exact TraceEquiv.refl _
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact ih₁.compat ih₂

variable (I) in
lemma equiv_of_length_two {a b : α} {w : List α} (h : TraceEquiv I [a, b] w) :
    w = [a, b] ∨ w = [b, a] := by
  have h_len := List.length_eq_two.mp (equiv_implies_length_eq I h).symm
  rcases h_len with ⟨c, d, hw⟩
  rw [hw] at h ⊢
  by_cases heq : a = b
  · subst heq
    have hc : c = a := by
      have h' := (equiv_implies_alph_eq I c h.symm).mp
      simp at h'
      exact h'
    have hd : d = a := by
      have h' := (equiv_implies_alph_eq I d h.symm).mp
      simp at h'
      exact h'
    simp [hc, hd]
  · have ha : a = c ∨ a = d := by
      have h' := (equiv_implies_alph_eq I a h).mp
      simp at h'
      exact h'
    have hb : b = c ∨ b = d := by
      have h' := (equiv_implies_alph_eq I b h).mp
      simp at h'
      exact h'
    rcases ha with hac | had <;> rcases hb with hbc | hbd
    · rw [← hbc] at hac
      contradiction
    · left
      simp [hac, hbd]
    · right
      simp [had, hbc]
    · rw [← hbd] at had
      contradiction

omit [DecidableEq α] in
variable (I) in
@[simp]
lemma equiv_of_singletons {a b : α} (h : TraceEquiv I [a] [b]) : a = b := by
  generalize hx : ([a] : List α) = x at h
  generalize hy : ([b] : List α) = y at h
  induction h generalizing a b with
  | swap _ _ _ =>
    simp at hx
  | refl _ =>
    simp [← hy] at hx
    exact hx
  | symm _ ih =>
    exact (ih hy hx).symm
  | trans t₁ t₂ _ _ =>
    have ht₁ := equiv_implies_alph_eq I a t₁
    have ht₂ := equiv_implies_alph_eq I a t₂
    have h_trans := ht₁.trans ht₂
    rw [← hx, ← hy] at h_trans
    simp at h_trans
    exact h_trans
  | compat t₁ t₂ ih₁ ih₂ =>
    rcases List.singleton_eq_append_iff.mp hx with ⟨hl₁, hl₃⟩ | ⟨hl₁, hl₃⟩
    <;> rcases List.singleton_eq_append_iff.mp hy with ⟨hl₂, hl₄⟩ | ⟨hl₂, hl₄⟩
    · exact ih₂ hl₃.symm hl₄.symm
    · have h_t₁ := equiv_implies_length_eq I t₁
      rw [hl₁, hl₂] at h_t₁
      contradiction
    · have h_t₁ := equiv_implies_length_eq I t₁
      rw [hl₁, hl₂] at h_t₁
      contradiction
    · exact ih₁ hl₁.symm hl₂.symm

variable (I) in
lemma equiv_and_ne_implies_independence {a b : α} (h : TraceEquiv I [a, b] [b, a]) (hne: a ≠ b):
    I.rel a b := by
  generalize hx : ([a, b] : List α) = x at h
  generalize hy : ([b, a] : List α) = y at h
  induction h generalizing a b with
  | swap c d r =>
    injection hx with ha
    injection hy with hb
    rw [ha, hb]
    exact r
  | refl _ =>
    injection hx.trans hy.symm with heq
    contradiction
  | symm _ ih =>
    exact I.symm b a (ih (hne.symm) hy hx)
  | trans t₁ _ ih₁ ih₂ =>
    rename_i t _
    rw [← hx] at t₁
    have ht := equiv_of_length_two I t₁
    rcases ht with h_tab | h_tba
    · exact ih₂ hne h_tab.symm hy
    · exact ih₁ hne hx h_tba.symm
  | compat t₁ t₂ ih₁ ih₂ =>
    rename_i l₁ l₂ l₃ l₄
    have h_l₁l₃ : l₁.length + l₃.length = 2 := by simp [← List.length_append, ← hx]
    have h_l₂l₄ : l₂.length + l₄.length = 2 := by simp [← List.length_append, ← hy]
    have h_t₁ := equiv_implies_length_eq I t₁
    have h_t₂ := equiv_implies_length_eq I t₂
    rcases Nat.add_eq_two_iff.mp h_l₁l₃ with ⟨hl₁, hl₃⟩ | ⟨hl₁, hl₃⟩ | ⟨hl₁, hl₃⟩
    <;> rcases Nat.add_eq_two_iff.mp h_l₂l₄ with ⟨hl₂, hl₄⟩ | ⟨hl₂, hl₄⟩ | ⟨hl₂, hl₄⟩
    · rw [List.length_eq_zero_iff.mp hl₁, List.nil_append] at hx
      rw [List.length_eq_zero_iff.mp hl₂, List.nil_append] at hy
      exact ih₂ hne hx hy
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    . rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rcases List.length_eq_one_iff.mp hl₁ with ⟨c, hc⟩
      rcases List.length_eq_one_iff.mp hl₂ with ⟨d, hd⟩
      simp [hc] at hx
      simp [hd] at hy
      rw [hc, hd] at t₁
      have h_cd := equiv_of_singletons I t₁
      rw [← hx.left, ← hy.left] at h_cd
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [List.length_eq_zero_iff.mp hl₃, List.append_nil] at hx
      rw [List.length_eq_zero_iff.mp hl₄, List.append_nil] at hy
      exact ih₁ hne hx hy

variable (I) in
lemma equiv_of_head_eq_implies_tail_equiv {u v w : List α}
    (h : TraceEquiv I (w ++ u) (w ++ v)) :
    TraceEquiv I u v := by
  induction w with
  | nil =>
    simp at h
    exact h
  | cons a w' ih =>
    simp at h
    replace h := cancellation_rule_left I a h
    simp at h
    exact ih h

variable (I) in
lemma equiv_of_tail_eq_implies_head_equiv {u v w : List α}
    (h : TraceEquiv I (u ++ w) (v ++ w)) :
    TraceEquiv I u v := by
  replace h := mirror_rule I h
  simp at h
  replace h := mirror_rule I (equiv_of_head_eq_implies_tail_equiv I h)
  simp at h
  exact h

variable (I) in
lemma tail_lemma {u v : List α} {a b : α}
    (h : TraceEquiv I (u ++ [a]) (v ++ [b])) (hne : a ≠ b) : -- (1.9)
    I.rel a b ∧ ∃ w, TraceEquiv I u (w ++ [b]) ∧ TraceEquiv I v (w ++ [a]) := by
  have h_cancel_a := by simpa [hne] using cancellation_rule I a h
  have h_cancel_b := by simpa [hne.symm] using (cancellation_rule I b h).symm
  have h_cancel_ab := by simpa [hne] using cancellation_rule I b h_cancel_a
  have h_cancel_b_concat_b := h_cancel_a.trans (h_cancel_ab.compat (TraceEquiv.refl [b])).symm
  have h_cancel_b_concat_ba := h_cancel_b_concat_b.compat (TraceEquiv.refl [a])
  have h_cancel_b_concat_ab := h_cancel_b.compat (TraceEquiv.refl [b])
  have h_tail := by simpa using h_cancel_b_concat_ab.symm.trans (h.symm.trans h_cancel_b_concat_ba)
  have h_ab_ba := equiv_of_head_eq_implies_tail_equiv I h_tail
  exact ⟨equiv_and_ne_implies_independence I h_ab_ba hne,
         ⟨u ÷ b,
          ⟨h_cancel_b_concat_b, h_cancel_b⟩⟩⟩

variable (I) in
lemma equiv_of_head_eq_tail_implies_mid_equiv {u v x y : List α}
    (h : TraceEquiv I (x ++ u ++ y) (x ++ v ++ y)) : -- (1.10)
    TraceEquiv I u v := by
  rw [List.append_assoc, List.append_assoc] at h
  replace h := equiv_of_head_eq_implies_tail_equiv I h
  replace h := equiv_of_tail_eq_implies_head_equiv I h
  exact h

variable (I) in
@[simp]
def independent (u v : List α) := ∀ a ∈ u, ∀ b ∈ v, I.rel a b

variable (I) in
lemma commutation_lemma {u v w : List α} {a : α}
    (h : TraceEquiv I (u ++ [a] ++ v) (w ++ [a])) (hav : a ∉ v) : -- (1.3.3)
    independent I [a] v := by
  induction v using List.induction_right generalizing w with
  | nil =>
    simp
  | snoc x b ih =>
    simp
    intro b' hb'
    simp at hb' hav
    rcases hav with ⟨hax, hab⟩
    rw [eq_comm] at hab
    rw [← List.append_assoc] at h
    have hr := (tail_lemma I h hab).left
    replace h := cancellation_rule I b h
    simp only [List.cancel_right_snoc, hab, ↓reduceIte] at h
    replace h := ih h hax
    simp at h
    rcases hb' with hb'x | hb'b
    · exact h b' hb'x
    · rw [← hb'b] at hr
      exact I.symm b' a hr

-- variable (I) in
-- lemma levi_lemma {u v x y : List α} (h : TraceEquiv I (u ++ v) (x ++ y)) : -- (1.11)
--     ∃ z₁ z₂ z₃ z₄, independent I z₂ z₃
--     ∧ TraceEquiv I u (z₁ ++ z₂) ∧ TraceEquiv I v (z₃ ++ z₄)
--     ∧ TraceEquiv I x (z₁ ++ z₃) ∧ TraceEquiv I y (z₂ ++ z₄) := by
--   sorry

end Trace
