import Mathlib.Data.Fintype.Basic
import TraceTheory.Basic

variable {α : Type*} [DecidableEq α]

namespace Trace

/-- A dependence is a finite, reflexive, and symmetric relation. -/
structure Dependence (α : Type*) where
  rel : α → α → Prop
  refl : ∀ a, rel a a
  symm: ∀ a b, rel a b → rel b a

/-- An independence is a finite, irreflexive, and symmetric relation. -/
structure Independence (α : Type*) where
  rel : α → α → Prop
  irrefl : ∀ a, ¬ rel a a
  symm : ∀ a b, rel a b → rel b a

/-- The Independence relation induced by a Dependence `D`. -/
def inducedIndependency {α : Type*} (D : Dependence α) : Independence α :=
  { rel    := fun a b => ¬ D.rel a b,
    irrefl := by
      intro a h
      exact h (D.refl a),
    symm   := by
      intro a b h
      exact h ∘ (D.symm b a) }

variable {I : Independence α}

variable (I) in
/--
The trace equivalence relation is the least congruence $\equiv$ such that for all symbols
$a$ and $b$, $(a,b) \in I \leftrightarrow ab \equiv ba$.

Intuitively, two strings (lists of symbols) are equivalent if one can be transformed into the other
by a finite sequence of swaps of adjacent independent symbols.

The relation is inductively generated by:
- **Swap:** If `I.rel a b`, then `[a, b]` is equivalent to `[b, a]` (swapping adjacent independent
  symbols).
- **Reflexivity:** Every word is equivalent to itself.
- **Symmetry:** If `w₁` is equivalent to `w₂`, then `w₂` is equivalent to `w₁`.
- **Transitivity:** If `w₁` is equivalent to `w₂` and `w₂` is equivalent to `w₃`, then `w₁` is
  equivalent to `w₃`.
- **Compatibility:** If `w₁` is equivalent to `w₂` and `w₃` is equivalent to `w₄`, then `w₁ ++ w₃`
  is equivalent to `w₂ ++ w₄`.
-/
inductive TraceEquiv : List α → List α → Prop
  | swap : ∀ a b, I.rel a b → TraceEquiv [a, b] [b, a]
  | refl : ∀ w₁, TraceEquiv w₁ w₁
  | symm : ∀ {w₁ w₂}, TraceEquiv w₁ w₂ → TraceEquiv w₂ w₁
  | trans : ∀ {w₁ w₂ w₃}, TraceEquiv w₁ w₂ → TraceEquiv w₂ w₃ → TraceEquiv w₁ w₃
  | compat : ∀ {w₁ w₂ w₃ w₄}, TraceEquiv w₁ w₂ → TraceEquiv w₃ w₄ → TraceEquiv (w₁ ++ w₃) (w₂ ++ w₄)

omit [DecidableEq α] in
variable (I) in
lemma length_eq {w₁ w₂ : List α} (h : TraceEquiv I w₁ w₂):
    w₁.length = w₂.length := by
  induction h with
  | swap _ _ _ =>
    rfl
  | refl _ =>
    rfl
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp [ih₁, ih₂]

omit [DecidableEq α] in
variable (I) in
lemma alphabet_eq {w₁ w₂ : List α} (a : α) (h : TraceEquiv I w₁ w₂) :
    (a ∈ w₁ ↔ a ∈ w₂) := by
  induction h with
  | swap _ _ _ =>
    simp
    exact Or.comm
  | refl _ =>
    exact Eq.to_iff rfl
  | symm _ ih =>
    exact Iff.symm ih
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact or_congr ih₁ ih₂

omit [DecidableEq α] in
variable (I) in
lemma mirror_rule {w₁ w₂ : List α} (h : TraceEquiv I w₁ w₂) : -- (1.6)
    TraceEquiv I w₁.reverse w₂.reverse := by
  induction h with
  | swap a b h =>
    simp
    exact TraceEquiv.swap b a (I.symm a b h)
  | refl w₁' =>
    exact TraceEquiv.refl w₁'.reverse
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact ih₂.compat ih₁

variable (I) in
lemma cancellation_rule {w₁ w₂ : List α} (a : α) (h : TraceEquiv I w₁ w₂) : -- (1.7)
    TraceEquiv I (w₁ ÷ a) (w₂ ÷ a) := by
  induction h with
  | swap b c hbc =>
    by_cases hab : a = b <;> by_cases hac : a = c
    · rw [← hab, ← hac]
      exact TraceEquiv.refl _
    · rw [← hab]
      simp [List.cancel_right, hac]
      exact TraceEquiv.refl _
    · rw [← hac]
      simp [List.cancel_right, hab]
      exact TraceEquiv.refl _
    · simp [List.cancel_right, hab, hac]
      exact TraceEquiv.swap b c hbc
  | refl _ =>
    exact TraceEquiv.refl _
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat t₁ t₂ ih₁ ih₂ =>
    rename_i l₃ _
    by_cases hal₃ : a ∈ l₃
    · have hal₄ := (alphabet_eq I a t₂).mp hal₃
      simp [hal₃, hal₄]
      exact t₁.compat ih₂
    · have hal₄ := (alphabet_eq I a t₂).mpr.mt hal₃
      simp [hal₃, hal₄]
      exact ih₁.compat t₂

variable (I) in
lemma cancellation_rule_left {w₁ w₂ : List α} (a : α) (h : TraceEquiv I w₁ w₂) :
    TraceEquiv I (w₁.cancel_left a) (w₂.cancel_left a) := by
  rw [List.cancel_left_eq_rev_cancel_right_rev, List.cancel_left_eq_rev_cancel_right_rev]
  exact mirror_rule I (cancellation_rule I a (mirror_rule I h))

variable (I) in
lemma projection_rule {w₁ w₂ : List α} (Sigma : Alphabet α) (h : TraceEquiv I w₁ w₂) : -- (1.8)
    TraceEquiv I (w₁.proj Sigma) (w₂.proj Sigma) := by
  induction h with
  | swap a b h =>
    by_cases ha : a ∈ Sigma <;> by_cases hb : b ∈ Sigma
    all_goals (
      simp [List.proj, ha, hb]
      try exact TraceEquiv.swap a b h
      try exact TraceEquiv.refl _
    )
  | refl _ =>
    exact TraceEquiv.refl _
  | symm _ ih =>
    exact ih.symm
  | trans _ _ ih₁ ih₂ =>
    exact ih₁.trans ih₂
  | compat _ _ ih₁ ih₂ =>
    simp
    exact ih₁.compat ih₂

variable (I) in
lemma equiv_length_eq_two {a b : α} {w : List α} (h : TraceEquiv I [a, b] w) :
    w = [a, b] ∨ w = [b, a] := by
  have h_len := List.length_eq_two.mp (length_eq I h).symm
  rcases h_len with ⟨c, d, hw⟩
  rw [hw] at h ⊢
  by_cases heq : a = b
  · subst heq
    have hc : c = a := by simpa using (alphabet_eq I c h.symm).mp
    have hd : d = a := by simpa using (alphabet_eq I d h.symm).mp
    simp [hc, hd]
  · have ha : a = c ∨ a = d := by simpa using (alphabet_eq I a h).mp
    have hb : b = c ∨ b = d := by simpa using (alphabet_eq I b h).mp
    rcases ha with hac | had <;> rcases hb with hbc | hbd
    · rw [← hbc] at hac
      contradiction
    · left
      simp [hac, hbd]
    · right
      simp [had, hbc]
    · rw [← hbd] at had
      contradiction

omit [DecidableEq α] in
variable (I) in
@[simp]
lemma equiv_singletons {a b : α} (h : TraceEquiv I [a] [b]) : a = b := by
  generalize hx : ([a] : List α) = x at h
  generalize hy : ([b] : List α) = y at h
  induction h generalizing a b with
  | swap _ _ _ =>
    simp at hx
  | refl _ =>
    simp [← hy] at hx
    exact hx
  | symm _ ih =>
    exact (ih hy hx).symm
  | trans t₁ t₂ _ _ =>
    have ht₁ := alphabet_eq I a t₁
    have ht₂ := alphabet_eq I a t₂
    have h_trans := ht₁.trans ht₂
    rw [← hx, ← hy] at h_trans
    simp at h_trans
    exact h_trans
  | compat t₁ t₂ ih₁ ih₂ =>
    rcases List.singleton_eq_append_iff.mp hx with ⟨hl₁, hl₃⟩ | ⟨hl₁, hl₃⟩
    <;> rcases List.singleton_eq_append_iff.mp hy with ⟨hl₂, hl₄⟩ | ⟨hl₂, hl₄⟩
    · exact ih₂ hl₃.symm hl₄.symm
    · have h_t₁ := length_eq I t₁
      rw [hl₁, hl₂] at h_t₁
      contradiction
    · have h_t₁ := length_eq I t₁
      rw [hl₁, hl₂] at h_t₁
      contradiction
    · exact ih₁ hl₁.symm hl₂.symm

variable (I) in
lemma indep_of_equiv_of_neq {a b : α} (h : TraceEquiv I [a, b] [b, a]) (hne: a ≠ b):
    I.rel a b := by
  generalize hx : ([a, b] : List α) = x at h
  generalize hy : ([b, a] : List α) = y at h
  induction h generalizing a b with
  | swap c d r =>
    injection hx with ha
    injection hy with hb
    rw [ha, hb]
    exact r
  | refl _ =>
    injection hx.trans hy.symm with heq
    contradiction
  | symm _ ih =>
    exact I.symm b a (ih (hne.symm) hy hx)
  | trans t₁ _ ih₁ ih₂ =>
    rename_i t _
    rw [← hx] at t₁
    have ht := equiv_length_eq_two I t₁
    rcases ht with h_tab | h_tba
    · exact ih₂ hne h_tab.symm hy
    · exact ih₁ hne hx h_tba.symm
  | compat t₁ t₂ ih₁ ih₂ =>
    rename_i l₁ l₂ l₃ l₄
    have h_l₁l₃ : l₁.length + l₃.length = 2 := by simp [← List.length_append, ← hx]
    have h_l₂l₄ : l₂.length + l₄.length = 2 := by simp [← List.length_append, ← hy]
    have h_t₁ := length_eq I t₁
    have h_t₂ := length_eq I t₂
    rcases Nat.add_eq_two_iff.mp h_l₁l₃ with ⟨hl₁, hl₃⟩ | ⟨hl₁, hl₃⟩ | ⟨hl₁, hl₃⟩
    <;> rcases Nat.add_eq_two_iff.mp h_l₂l₄ with ⟨hl₂, hl₄⟩ | ⟨hl₂, hl₄⟩ | ⟨hl₂, hl₄⟩
    · rw [List.length_eq_zero_iff.mp hl₁, List.nil_append] at hx
      rw [List.length_eq_zero_iff.mp hl₂, List.nil_append] at hy
      exact ih₂ hne hx hy
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    . rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rcases List.length_eq_one_iff.mp hl₁ with ⟨c, hc⟩
      rcases List.length_eq_one_iff.mp hl₂ with ⟨d, hd⟩
      simp [hc] at hx
      simp [hd] at hy
      rw [hc, hd] at t₁
      have h_cd := equiv_singletons I t₁
      rw [← hx.left, ← hy.left] at h_cd
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [hl₁, hl₂] at h_t₁
      contradiction
    · rw [List.length_eq_zero_iff.mp hl₃, List.append_nil] at hx
      rw [List.length_eq_zero_iff.mp hl₄, List.append_nil] at hy
      exact ih₁ hne hx hy

variable (I) in
lemma equiv_cancel_left {u v w : List α}
    (h : TraceEquiv I (w ++ u) (w ++ v)) :
    TraceEquiv I u v := by
  induction w with
  | nil =>
    simp at h
    exact h
  | cons a w' ih =>
    simp at h
    replace h := cancellation_rule_left I a h
    simp at h
    exact ih h

variable (I) in
lemma equiv_cancel_right {u v w : List α}
    (h : TraceEquiv I (u ++ w) (v ++ w)) :
    TraceEquiv I u v := by
  replace h := mirror_rule I h
  simp at h
  replace h := mirror_rule I (equiv_cancel_left I h)
  simp at h
  exact h

variable (I) in
lemma indep_and_decomp_of_equiv_of_neq_tail {u v : List α} {a b : α}
    (h : TraceEquiv I (u ++ [a]) (v ++ [b])) (hne : a ≠ b) : -- (1.9)
    I.rel a b ∧ ∃ w, TraceEquiv I u (w ++ [b]) ∧ TraceEquiv I v (w ++ [a]) := by
  have h_cancel_a := by simpa [hne] using cancellation_rule I a h
  have h_cancel_b := by simpa [hne.symm] using (cancellation_rule I b h).symm
  have h_cancel_ab := by simpa [hne] using cancellation_rule I b h_cancel_a
  have h_cancel_b_concat_b := h_cancel_a.trans (h_cancel_ab.compat (TraceEquiv.refl [b])).symm
  have h_cancel_b_concat_ba := h_cancel_b_concat_b.compat (TraceEquiv.refl [a])
  have h_cancel_b_concat_ab := h_cancel_b.compat (TraceEquiv.refl [b])
  have h_tail := by simpa using h_cancel_b_concat_ab.symm.trans (h.symm.trans h_cancel_b_concat_ba)
  have h_ab_ba := equiv_cancel_left I h_tail
  exact ⟨indep_of_equiv_of_neq I h_ab_ba hne,
         ⟨u ÷ b,
          ⟨h_cancel_b_concat_b, h_cancel_b⟩⟩⟩

variable (I) in
lemma equiv_cancel_left_right {u v x y : List α}
    (h : TraceEquiv I (x ++ u ++ y) (x ++ v ++ y)) : -- (1.10)
    TraceEquiv I u v := by
  rw [List.append_assoc, List.append_assoc] at h
  replace h := equiv_cancel_left I h
  replace h := equiv_cancel_right I h
  exact h

variable (I) in
@[simp]
def independent (u v : List α) := ∀ a ∈ u, ∀ b ∈ v, I.rel a b

variable (I) in
lemma indep_of_equiv_rightmost_symbol {u v w : List α} {a : α}
    (h : TraceEquiv I (u ++ [a] ++ v) (w ++ [a])) (hav : a ∉ v) : -- (1.3.3)
    independent I [a] v := by
  induction v using List.induction_right generalizing w with
  | nil =>
    simp
  | snoc x b ih =>
    simp
    intro b' hb'
    simp at hb' hav
    rcases hav with ⟨hax, hab⟩
    rw [eq_comm] at hab
    rw [← List.append_assoc] at h
    have hr := (indep_and_decomp_of_equiv_of_neq_tail I h hab).left
    replace h := cancellation_rule I b h
    replace h := by simpa only [List.cancel_right_snoc, hab, ↓reduceIte] using h
    replace h := by simpa using ih h hax
    rcases hb' with hb'x | hb'b
    · exact h b' hb'x
    · rw [← hb'b] at hr
      exact I.symm b' a hr

lemma right_most_occurrence {w : List α} {a : α} (h : a ∈ w) :
    ∃ w' w'', w = w' ++ [a] ++ w'' ∧ a ∉ w'' := by
  induction w using List.induction_right with
  | nil =>
    contradiction
  | snoc v b ih =>
    by_cases hab : a = b
    · use v, []
      simp [hab]
    · simp [hab] at h
      have ⟨w', w'', ⟨h_concat, h_in⟩⟩ := ih h
      use w', w'' ++ [b]
      simp [h_concat, h_in, hab]

omit [DecidableEq α] in
variable (I) in
lemma equiv_of_indep_symb_commute_list {w : List α} {a : α} (h : independent I [a] w) :
    TraceEquiv I (w ++ [a]) ([a] ++ w) := by
  induction w using List.induction_right with
  | nil =>
    exact TraceEquiv.refl [a]
  | snoc w' b ih =>
    simp at h
    have haw' : independent I [a] w' := by
      simp
      intro b' hb'
      exact h b' (Or.intro_left (b' = b) hb')
    have ht := ih haw'
    have hb := ht.compat (TraceEquiv.refl [b])
    have hab : TraceEquiv I (w' ++ [b] ++ [a]) (w' ++ [a] ++ [b]) := by
      have hr := h b
      simp at hr
      simp
      exact (TraceEquiv.refl w').compat (TraceEquiv.swap b a (I.symm a b hr))
    exact hab.trans hb

omit [DecidableEq α] in
variable (I) in
lemma indep_of_indep_of_equiv {w₁ w₂ w₃: List α}
    (h : independent I w₁ w₂) (ht : TraceEquiv I w₂ w₃) :
    independent I w₁ w₃ := by
  intro a ha b hb
  have h_alph := alphabet_eq I b ht
  have hbw₂ := h_alph.mpr hb
  exact h a ha b hbw₂

omit [DecidableEq α] in
variable (I) in
lemma indep_of_concat {w₁ w₂ w₃: List α} (h : independent I w₁ (w₂ ++ w₃)) :
    independent I w₁ w₂ ∧ independent I w₁ w₃ := by
  unfold independent at *
  constructor
  · intro a ha b hb
    apply h
    apply ha
    apply List.mem_append.mpr
    left
    apply hb
  · intro a ha b hb
    apply h
    apply ha
    apply List.mem_append.mpr
    right
    apply hb

variable (I) in
theorem levi_lemma {u v x y : List α} (h : TraceEquiv I (u ++ v) (x ++ y)) : -- (1.11)
    ∃ z₁ z₂ z₃ z₄, independent I z₂ z₃
    ∧ TraceEquiv I u (z₁ ++ z₂) ∧ TraceEquiv I v (z₃ ++ z₄)
    ∧ TraceEquiv I x (z₁ ++ z₃) ∧ TraceEquiv I y (z₂ ++ z₄) := by
  induction y using List.induction_right generalizing u v with
  | nil =>
    use u, [], v, []
    simp [List.append_nil, TraceEquiv.refl]
    simp [List.append_nil] at h
    exact TraceEquiv.symm h
  | snoc w e ih =>
    by_cases hev : e ∈ v
    · have ⟨v', v'', ⟨hv, hv''⟩⟩ := right_most_occurrence hev
      have h_cancel := cancellation_rule I e h
      rw [hv, ← List.append_assoc, List.cancel_right_over_concat] at h_cancel
      simp [hv''] at h_cancel
      have ⟨z₁', z₂', z₃', z₄', ⟨h_indep, ht₁, ht₂, ht₃, ht₄⟩⟩ := ih h_cancel
      use z₁', z₂', z₃', z₄' ++ [e], h_indep
      replace ht₄ := ht₄.compat (TraceEquiv.refl [e])
      replace ht₂ := ht₂.compat (TraceEquiv.refl [e])
      have he : TraceEquiv I (v'' ++ [e]) ([e] ++ v'') := by
        rw [hv, ← List.append_assoc, ← List.append_assoc, ← List.append_assoc] at h
        have h_indep := indep_of_equiv_rightmost_symbol I h hv''
        exact equiv_of_indep_symb_commute_list I h_indep
      have hv'e := TraceEquiv.symm ((TraceEquiv.refl v').compat he)
      rw [← List.append_assoc, ← List.append_assoc, ← hv] at hv'e
      replace ht₂ := hv'e.trans ht₂
      rw [List.append_assoc] at ht₂ ht₄
      exact ⟨ht₁, ht₂, ht₃, ht₄⟩
    · have heu : e ∈ u := by
        have h_alph := alphabet_eq I e h
        simp at h_alph
        exact Or.resolve_right h_alph hev
      have ⟨u', u'', ⟨hu, hu''⟩⟩ := right_most_occurrence heu
      have h_cancel := cancellation_rule I e h
      rw [hu, ← List.append_assoc, List.cancel_right_over_concat] at h_cancel
      simp only [hev, ↓reduceIte] at h_cancel
      rw [List.cancel_right_over_concat] at h_cancel
      simp [hu'', -List.append_assoc] at h_cancel
      have ⟨z₁', z₂', z₃', z₄', ⟨h_indep, ht₁, ht₂, ht₃, ht₄⟩⟩ := ih h_cancel
      have h_indep_e : independent I [e] (u'' ++ v) := by
         rw [hu, ← List.append_assoc, List.append_assoc] at h
         exact indep_of_equiv_rightmost_symbol I h (List.not_mem_append hu'' hev)
      replace h_indep : independent I (z₂' ++ [e]) z₃' := by
        intro a ha b hb
        simp at ha h_indep
        rcases ha with haz₂' | hae
        · exact h_indep a haz₂' b hb
        · have h_indep_ev := (indep_of_concat I h_indep_e).right
          have h_equiv := indep_of_indep_of_equiv I h_indep_ev ht₂
          simp [← hae] at h_equiv
          apply h_equiv
          left
          apply hb
      use z₁', z₂' ++ [e], z₃', z₄', h_indep
      rw [hu, ← List.append_assoc]
      have heu'' : TraceEquiv I (u'' ++ [e]) ([e] ++ u'') :=
        equiv_of_indep_symb_commute_list I (indep_of_concat I h_indep_e).left
      have hu'e := TraceEquiv.symm ((TraceEquiv.refl u').compat heu'')
      rw [← List.append_assoc, ← List.append_assoc] at hu'e
      replace ht₁ := hu'e.trans (ht₁.compat (TraceEquiv.refl [e]))
      have hez₄' : TraceEquiv I (z₄' ++ [e]) ([e] ++ z₄') := by
        have h_indep_ev := (indep_of_concat I h_indep_e).right
        have h_indep_ez₃'z₄' := indep_of_indep_of_equiv I h_indep_ev ht₂
        exact equiv_of_indep_symb_commute_list I (indep_of_concat I h_indep_ez₃'z₄').right
      have hz₄'e := (TraceEquiv.refl z₂').compat hez₄'
      rw [← List.append_assoc, ← List.append_assoc] at hz₄'e
      replace ht₄ := (ht₄.compat (TraceEquiv.refl [e])).trans hz₄'e
      exact ⟨ht₁, ht₂, ht₃, ht₄⟩

end Trace
